# News volatility prediction

Описание: Задача предсказания хаотичности и волатильности рынка во время выхода новости.

В качестве хаотичности будут использоваться следующие признаки:
- Range efficiency (in next N bars);
- Directional Noise Index (in next N bars);
- Range (in next N bars).

**Range efficiency** расчитывается как отношение разницы максимальной и минимальной цены (за N баров) к сумме всех диапазонов свечей (также за N баров).
Чем ближе значение к 1, тем более однонаправленным является движение. Чем ниже значение *RE*, тем больше внутренних движений произошло за N баров.

**Directional Noise Index** рассчитывается похожим образом, но вместо разницы максимальной и минимальной цены (за N баров), берется сумма абсолютных разниц между ценой закрытия и ценой открытия, которое делится на сумму всех диапазонов свечей (также за N баров). Значение близкое к 1 говорит о том, что движение является однонаправленным, а значение близкое к 0 говорит о том, что движение является хаотичным.


Фичи для ML модели:
- True Range (нормализовать)
- ATR (тоже нормализовать)
- ADX
- Close % change
- Volume % change
- Cumulative Volume % change
- Range efficiency *before news* (lags: 1, 3, 6, 12, 24)
- Directional noise index *before news* (lags: 1, 3, 6, 12, 24)
- Hurst exponent *before news* (lags: 1, 3, 6, 12, 24)

## Загрузка новостей

In [1]:
from typing import Literal

import pandas as pd
import numpy as np
import pytz
from scipy.stats import entropy

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

from warnings import filterwarnings
filterwarnings('ignore')

from tqdm.auto import tqdm
tqdm.pandas()

In [2]:
moscow_tz = pytz.timezone('Europe/Moscow')
news_tz = pytz.timezone('Asia/Tehran')

In [3]:
PATH_TO_NEWS = "C:/Users/user/Documents/projects/ALGO/algotrading/dataset/economy_calendar/forex_factory_cache.csv"
news = pd.read_csv(PATH_TO_NEWS)
news.head()

,DateTime,Currency,Impact,Event,Actual,Forecast,Previous,Detail
0,2007-01-01T04:30:00+03:30,CNY,High Impact Expected,Manufacturing PMI,54.8,NaN,55.3,Source: CFLP (latest release) | Measures: Leve...
1,2007-01-01T23:59:59+03:30,CAD,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: Canadian banks will be closed in ...
2,2007-01-01T23:59:59+03:30,USD,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: US banks will be closed in observ...
3,2007-01-01T23:59:59+03:30,CNY,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: Chinese banks will be closed in o...
4,2007-01-01T23:59:59+03:30,EUR,Non-Economic,German Bank Holiday,NaN,NaN,NaN,FF Notice: The European Central Bank's Trans-E...

## Check Detail column

In [5]:
news['Detail'].to_list()[:10]

["Source: CFLP (latest release) | Measures: Level of a diffusion index based on surveyed purchasing managers in the manufacturing industry; | Usual Effect: 'Actual' greater than 'Forecast' is good for currency; | Frequency: Released monthly, on the last day of the current month; | Next Release: Feb 1, 2007 | FF Notes: Above 50.0 indicates industry expansion, below indicates contraction. Tends to have more impact when it's released ahead of the Caixin Manufacturing PMI because the reports are tightly correlated. Chinese data can have a broad impact on the currency markets due to China's influence on the global economy and investor sentiment; | Why Traders Care: It's a leading indicator of economic health - businesses react quickly to market conditions, and their purchasing managers hold perhaps the most current and relevant insight into the company's view of the economy; | Derived Via: Survey of 3,000 purchasing managers which asks respondents to rate the relative level of business conditions including employment, production, new orders, prices, supplier deliveries, and inventories; | Acro Expand: China Federation of Logistics and Purchasing (CFLP), Purchasing Managers' Index (PMI);",
 "Description: Canadian banks will be closed in observance of New Year's Day; | Usual Effect: Low liquidity and irregular volatility; | Next Release: Apr 6, 2007 | FF Notes: Most Forex brokers remain open for every holiday except Christmas and New Year's Day. Stock markets and banks have slightly different holiday schedules; | Why Traders Care: Banks facilitate the majority of foreign exchange volume. When they are closed the market is less liquid and speculators become a more dominant market influence. This can lead to both abnormally low and abnormally high volatility;",
 "Description: US banks will be closed in observance of New Year's Day; | Usual Effect: Low liquidity and irregular volatility; | Next Release: Jan 15, 2007 | FF Notes: Most Forex brokers remain open for every holiday except Christmas and New Year's Day. Stock markets and banks have slightly different holiday schedules; | Why Traders Care: Banks facilitate the majority of foreign exchange volume. When they are closed the market is less liquid and speculators become a more dominant market influence. This can lead to both abnormally low and abnormally high volatility;",
 "Description: Chinese banks will be closed in observance of New Year's Day; | Usual Effect: Low liquidity and irregular volatility; | Next Release: Jan 2, 2007 | FF Notes: Most Forex brokers remain open for every holiday except Christmas and New Year's Day. Stock markets and banks have slightly different holiday schedules; | Why Traders Care: Banks facilitate the majority of foreign exchange volume. When they are closed the market is less liquid and speculators become a more dominant market influence. This can lead to both abnormally low and abnormally high volatility;",
 "FF Notice: The European Central Bank's Trans-European Automated Real-time Gross Settlement Express Transfer (TARGET) system will be closed for this holiday, which tends to have a substantial impact on liquidity; | Description: German banks will be closed in observance of New Year's Day; | Usual Effect: Low liquidity and irregular volatility; | Next Release: Apr 6, 2007 | FF Notes: Most Forex brokers remain open for every holiday except Christmas and New Year's Day. Stock markets and banks have slightly different holiday schedules; | Why Traders Care: Banks facilitate the majority of foreign exchange volume. When they are closed the market is less liquid and speculators become a more dominant market influence. This can lead to both abnormally low and abnormally high volatility;",
 "Description: Australian banks will be closed in observance of New Year's Day; | Usual Effect: Low liquidity and irregular volatility; | Next Release: Jan 26, 2007 | FF Notes: Most Forex brokers remain open for every holiday except Christmas and New Year's Day. Stock markets and banks have slightly different holiday schedules; | Why Traders Care: Banks facilitate the majority of foreign exchange volume. When they are closed the market is less liquid and speculators become a more dominant market influence. This can lead to both abnormally low and abnormally high volatility;",
 "Description: Japanese banks will be closed in observance of the 4-day Bank Holiday; | Usual Effect: Low liquidity and irregular volatility; | Next Release: Jan 2, 2007 | FF Notes: Most Forex brokers remain open for every holiday except Christmas and New Year's Day. Stock markets and banks have slightly different holiday schedules; | Why Traders Care: Banks facilitate the majority of foreign exchange volume. When they are closed the market is less liquid and speculators become a more dominant market influence. This can lead to both abnormally low and abnormally high volatility;",
 "Description: UK banks will be closed in observance of New Year's Day; | Usual Effect: Low liquidity and irregular volatility; | Next Release: Apr 6, 2007 | FF Notes: Most Forex brokers remain open for every holiday except Christmas and New Year's Day. Stock markets and banks have slightly different holiday schedules; | Why Traders Care: Banks facilitate the majority of foreign exchange volume. When they are closed the market is less liquid and speculators become a more dominant market influence. This can lead to both abnormally low and abnormally high volatility;",
 "FF Notice: The European Central Bank's Trans-European Automated Real-time Gross Settlement Express Transfer (TARGET) system will be closed for this holiday, which tends to have a substantial impact on liquidity; | Description: Italian banks will be closed in observance of New Year's Day; | Usual Effect: Low liquidity and irregular volatility; | Next Release: Apr 9, 2007 | FF Notes: Most Forex brokers remain open for every holiday except Christmas and New Year's Day. Stock markets and banks have slightly different holiday schedules; | Why Traders Care: Banks facilitate the majority of foreign exchange volume. When they are closed the market is less liquid and speculators become a more dominant market influence. This can lead to both abnormally low and abnormally high volatility;",
 "Description: Swiss banks will be closed in observance of New Year's Day; | Usual Effect: Low liquidity and irregular volatility; | Next Release: Jan 2, 2007 | FF Notes: Most Forex brokers remain open for every holiday except Christmas and New Year's Day. Stock markets and banks have slightly different holiday schedules; | Why Traders Care: Banks facilitate the majority of foreign exchange volume. When they are closed the market is less liquid and speculators become a more dominant market influence. This can lead to both abnormally low and abnormally high volatility;"]

In [9]:
from collections import Counter
from tqdm import tqdm
import re

In [14]:
c = Counter()
for line in tqdm(news['Detail'].to_list()):
    try:
        words = re.findall(r"[A-Za-z][A-Za-z\s]*:", line)
        c.update(words)
    except Exception as e:
        pass

100%|██████████| 83427/83427 [00:08<00:00, 10211.58it/s]

In [12]:
c

Counter({'Next Release:': 83158,
         'Source:': 80867,
         'Usual Effect:': 80448,
         'Frequency:': 72614,
         'FF Notes:': 68617,
         'Why Traders Care:': 68115,
         'Measures:': 66678,
         'Acro Expand:': 47082,
         'Also Called:': 36975,
         'Derived Via:': 21886,
         'Description:': 10753,
         'Speaker:': 8434,
         'FF Notice:': 5179,
         'parts:': 145,
         'Monetary Policy:': 6,
         'Financial Stability:': 4,
         'Central Banking:': 4,
         'Central Banking in the Shadows:': 4,
         'At the heart of policy:': 4,
         'The euro at ten:': 3,
         'The Global Economy:': 3,
         'The Euro and the Dollar:': 2,
         'UK Monetary Policy:': 2,
         'Global Imbalances:': 2,
         'Economic Challenges:': 2,
         'The Challenges:': 2,
         'After the Crisis:': 2,
         'Central Bank statistics:': 2,
         's competitive imperative:': 2,
         'Fulfilling the Full Employment Mandate:': 2,
         'Global Economy:': 2,
         'Resolution Conference:': 2,
         'and Federal Reserve Bank of New York Conference:': 2,
         'Tying Down the Anchor:': 2,
         'Hall of Mirrors:': 2,
         'Libor:': 2,
         'Tackling climate for real:': 2,
         'Central banks and climate change:': 2,
         'Central bank independence and new risks:': 2,
         'CBDCs:': 2,
         'Digital Euro:': 2,
         'Talking Economics:': 2,
         'The Discount Window:': 2,
         'Border Payments:': 2,
         'Easy Money:': 1,
         'The Changing Pattern of Savings:': 1,
         's Growth:': 1,
         'Embracing the Challenge of Free Trade:': 1,
         'Banks in the Payments System:': 1,
         'Nonbanks in the Payments System:': 1,
         'The Future of Payments:': 1,
         'Globalization and Capital Markets:': 1,
         'Encouraging Responsible Mortgage Lending:': 1,
         'Central Banking and Political Economy:': 1,
         's Payments System:': 1,
         'Highly Leveraged Institutions and Financial Stability:': 1,
         'The Meaning of Internal Balance:': 1,
         'The Asian Crisis:': 1,
         'Monetary Policy and Government Debt:': 1,
         'Challenges to the International Monetary System:': 1,
         'Globalization and Financial Markets:': 1,
         'Ontario in the Global Economy:': 1,
         'A Tale of Two Shocks:': 1,
         'Money and Credit:': 1,
         'Recent and Prospective Developments in Monetary Policy Transparency and Communications:': 1,
         'Transparency:': 1,
         'Monetary Policy and Uncertainty:': 1,
         'The Return of the Credit Cycle:': 1,
         'Leveraged Losses:': 1,
         'meeting Summit:': 1,
         'The Current Financial Challenges:': 1,
         'Monetary Policy and Inflation:': 1,
         'Addressing Weaknesses in the Global Financial Markets:': 1,
         'The Changing Business of Banking:': 1,
         'Swiss Trade With the World:': 1,
         'Opportunity Knocks:': 1,
         'Walking the Tightrope:': 1,
         'A strategic vision for statistics:': 1,
         'The Australian Economy:': 1,
         'Asset Price Bubbles:': 1,
         'Central banks in action:': 1,
         'Capitalizing on the Commodity Boom:': 1,
         'Work in Progress:': 1,
         'The United States in the International Financial System:': 1,
         'Agenda for Europe:': 1,
         'Measuring Inflation:': 1,
         'The Quest for Confidence:': 1,
         'The Euro at Ten:': 1,
         'Fifteen months of financial turmoil:': 1,
         'Risk Transfer:': 1,
         'Run Economic Challenges:': 1,
         'Stabilizing the Housing Market:': 1,
         'Stabilizing the Housing Markets:': 1,
         'Financial Market Turmoil:': 1,
         'Payment System Reforms:': 1,
         'Stable Finance:': 1,
         'The Global Financial Crisis:': 1,
         's Financial Sector:': 1,
         'Financial Crisis:': 1,
         'Canada and the Economic Crisis:': 1,
         'The International Financial Crisis:': 1,
         'The Three Rs:': 1,
         'Short Selling:': 1,
         's Balance Sheet:': 1,
         'Monetary Policy Research and the Financial Crisis:': 1,
         'Economics Made Easy:': 1,
         'Central Banking Revealed:': 1,
         'The Transatlantic Marketplace:': 1,
         'Unusual and Exigent:': 1,
         'The US Economy:': 1,
         'Banking regulation:': 1,
         'Economic Policy:': 1,
         'Shaping a New World:': 1,
         'Beyond the Exit:': 1,
         'Woman and Money:': 1,
         'Understanding the Housing Collapse:': 1,
         'Up from the Ashes:': 1,
         'Central Banking after the Crisis:': 1,
         'The Squam Lake Report:': 1,
         'Small Business Credit:': 1,
         's Monetary Policy Framework:': 1,
         'Financial Services Board Reform Conference:': 1,
         'at the Federal Reserve Bank Conference:': 1,
         'Global Ethical Standards:': 1,
         'th Annual Economic Policy Conference:': 1,
         'The Financial Stability Oversight Council:': 1,
         'A Return to Jekyll Island:': 1,
         'Moving Forward:': 1,
         'Monetary policy challenges:': 1,
         'The Future of Financial Services:': 1,
         'The euro:': 1,
         'Economic Growth and Stability:': 1,
         'Years of Innovation:': 1,
         'Changing Circumstances:': 1,
         'Summit of the Americas:': 1,
         'Monetary and Fiscal policy:': 1,
         'Wire Act:': 1,
         'Back to Work:': 1,
         'New Building Blocks for Jobs and Economic Growth:': 1,
         'Explaining Dissent:': 1,
         'Towards a more integrated and stable Europe:': 1,
         'European Post Trading:': 1,
         'Econometrics for Policy Analysis:': 1,
         'A Report on the Economy:': 1,
         's Economic Outlook:': 1,
         'Federal Reserve Aid to the Euro zone:': 1,
         'The Fed and the Economy:': 1,
         'US Overview:': 1,
         'Twist and Shout:': 1,
         'Banks and Bank Lending:': 1,
         'Foreign Exchange Regimes:': 1,
         'and Financial Stability:': 1,
         'Japan in the Global Economy:': 1,
         'Thoughts on Two Other Sources of Financial Instability:': 1,
         'Financial System Connectedness and Systemic Risk:': 1,
         's Workers:': 1,
         'Wall Street Reform:': 1,
         'From New College to the Fed:': 1,
         'Strong franc and high current account surplus:': 1,
         'Fiscal and Monetary Policy:': 1,
         'Currency Wars:': 1,
         'Maintaining Financial Stability:': 1,
         'Income Communities:': 1,
         'Credit:': 1,
         'Regulatory Landscapes:': 1,
         'A Century of US Central Banking:': 1,
         'Years of the Federal Reserve:': 1,
         'Closer to the Edge:': 1,
         'Shifting gear:': 1,
         'at the International Conference:': 1,
         'The Canadian Payments System:': 1,
         'Crisis:': 1,
         'The Australian Dollar:': 1,
         's Monetary Union:': 1,
         'Due to speak at the International Association for Research on Income and Wealth and University of New South Wales Conference on Productivity:': 1,
         'Asset management at the SNB:': 1,
         'Achieving a sustainable recovery:': 1,
         'Prospects for the UK Economy:': 1,
         'A Broader Role for Central Banks Following the Crisis:': 1,
         'Against the Moral Hazzard:': 1,
         'Forward Guidance:': 1,
         'st Century:': 1,
         'Adding Fuel to the Engine:': 1,
         'years:': 1,
         'Based Policy:': 1,
         'Realising our potential:': 1,
         'Financial Regulation:': 1,
         'The Great Recession:': 1,
         'Due to speak at the Federal Reserve Bank of Kansas City Economic Symposium:': 1,
         'Due to participate in a panel discussion at the Federal Reserve Bank of Kansas City Economic Symposium:': 1,
         'Louis Federal Reserve Webinar and Conference Call:': 1,
         'The Federal Reserve and Monetary Policy:': 1,
         'Banking Union and Regulatory Reforms:': 1,
         'Due to speak at the Switzerland at the heart of Europe:': 1,
         'Challenges in the euro zone:': 1,
         'The Nonbank Financial Sector:': 1,
         'The Way Home:': 1,
         'From Country Banks to SIFIs:': 1,
         'Due to speak at the Launch of Financial Integration in the Asia Pacific:': 1,
         'Frank at Five:': 1,
         'Weathering the storm:': 1,
         'The Fed at Crossroads:': 1,
         'The Bank of England in Europe:': 1,
         'The Dappled World:': 1,
         'Language after Liftoff:': 1,
         'Current Account Deficits during Heightened Risk:': 1,
         's Great Transition:': 1,
         'Market and Funding Liquidity:': 1,
         'Unconventional wisdom:': 1,
         'and Monetary Policy:': 1,
         'Track Adjustment:': 1,
         'How the World REALLY Works:': 1,
         'Monetary Policy after Quantitative Easing:': 1,
         'Financial Markets and Implementation of Monetary Policy:': 1,
         'Negative Interest:': 1,
         'Election:': 1,
         'Responders of First or Last Resort:': 1,
         'Building a More Robust Financial System:': 1,
         'Moving away from the expansive monetary policy:': 1,
         'Cashing Out:': 1,
         'Blockchain and payments:': 1,
         'Independence of Central Banks after the Financial Crisis:': 1,
         'The Phillips curve:': 1,
         'High current account surplus of Switzerland:': 1,
         'US Economy:': 1,
         'What to Expect From the Lower Bound on Interest Rates:': 1,
         'The Fall in Productivity Growth:': 1,
         'years after the Global Financial Crisis:': 1,
         'Today and tomorrow:': 1,
         'Inflation targeting in New Zealand:': 1,
         'Closing the Gap:': 1,
         'Innovation and Entrepreneurship:': 1,
         'Productivity Matters:': 1,
         'Let Me Be Clear:': 1,
         'years after the storm:': 1,
         'The Outlook for Tomorrow:': 1,
         'National digital currencies:': 1,
         'Ten years after the crisis:': 1,
         'Balancing act:': 1,
         'Due to discuss the new book by Alan Greenspan and Adrian Wooldridge:': 1,
         'Capitalism in America:': 1,
         'Federal Reserve chairs:': 1,
         'Fed Listens:': 1,
         'The Community Reinvestment Act:': 1,
         'Capital Market Development and FinTech Revolution:': 1,
         'Managing Capital Flows:': 1,
         'Central Bank Digital Currencies:': 1,
         'Price Stability:': 1,
         'Marriner Eccles:': 1,
         'Climate Risks and Central Banks:': 1,
         'Unconventional Monetary Policy:': 1,
         'Navigating the Crosscurrents:': 1,
         'Our Economic Destiny:': 1,
         'Monetary policy during pandemics:': 1,
         'big challenges:': 1,
         'The Economic Outlook:': 1,
         'Understanding the gap:': 1,
         'Economic Justice:': 1,
         'and the Global Economy:': 1,
         'Central Bank Digital Currency and the Private Sector:': 1,
         'Leaders Panel:': 1,
         'Monetary policy implementation:': 1,
         'A Global Tipping Point:': 1,
         'The Power of Creative Destruction:': 1,
         'panel:': 1,
         'Fiscal and Monetary Stabilization in Europe:': 1,
         'Central banks and the green transition:': 1,
         'From strategy to decision:': 1,
         'The challenges of this century:': 1,
         'Future of Financial Services:': 1,
         'crisis Central Banking in Challenging Times:': 1,
         'at the Inflation:': 1,
         'Forward Guidance as a Monetary Policy Tool:': 1,
         's mandate:': 1,
         'Ground Zero:': 1,
         'Sustainability and Money:': 1,
         'Returning Inflation to Target:': 1,
         'Policy Solutions:': 1,
         'The World Economy:': 1,
         'Monetary Policy for conventional times:': 1,
         'Global Economic Outlook:': 1,
         'inflation pressures:': 1,
         's opportunities:': 1,
         'The results of rising rates:': 1,
         'Monetary policy since the pandemic:': 1,
         'The Return of Inflation:': 1,
         'pandemic challenges:': 1,
         'The Macroeconomic Outlook:': 1,
         'The Great Debate:': 1,
         'Battle Against Inflation:': 1,
         'Challenges for Policy After the Return of Inflation:': 1,
         'Facing the great systemic shocks:': 1,
         'The New Trilemma of Macro Economic Policy:': 1,
         'IMF Seminar:': 1,
         'Germany:': 1,
         'Banking sector turbulences:': 1,
         'Digital Money Revolution:': 1,
         'Inflation Tide after Peak:': 1,
         'All Change:': 1,
         'and Technology:': 1,
         'Community Reinvestment Act Modernization:': 1,
         'Investing for Growth:': 1,
         'Hard times:': 1,
         'Risks and Uncertainty in Monetary Policy:': 1,
         'Interest rates and foreign exchange interventions:': 1,
         's Housing Crisis:': 1,
         'Growth:': 1,
         'The future of CBDCs:': 1,
         'too high:': 1,
         'Cost of Capital:': 1,
         's growth path with investments:': 1,
         'UK inflation:': 1,
         'The Federal Reserve:': 1,
         'German Economy:': 1,
         'Geoeconomic Fragmentation:': 1,
         'Resilience and Renewal:': 1,
         'Global Economics:': 1,
         'Beyond Crisis:': 1,
         'in the monetary policy universe:': 1,
         'Financing the Transition to Greenhouse Gas Neutrality:': 1,
         'The Policy Strategy:': 1,
         'Inflation Expectations and Reality:': 1})

In [44]:
main_details = ['Next Release',
                'Source',
                'Usual Effect',
                'Frequency',
                'FF Notes',
                'Why Traders Care',
                'Measures',
                'Acro Expand',
                'Also Called',
                'Derived Via',
                'Description',
                'Speaker',
                'FF Notice']

In [45]:
def extract_field_text_from_event(text: str, field: str):
    try:
        return re.findall(fr"{field}:\s*([^|]+)", text)[0]
    except Exception as e:
        return None

In [46]:
for main_detail in tqdm(main_details):
    news[main_detail] = news['Detail'].apply(lambda x: extract_field_text_from_event(x, main_detail))

100%|██████████| 13/13 [00:01<00:00,  9.38it/s]

In [81]:
news['Next Release'] = pd.to_datetime(news['Next Release'], errors='coerce')

In [87]:
news['utc_dt'] = pd.to_datetime(news['DateTime'], utc=True).dt.tz_convert(moscow_tz)
news['Next Release'] = pd.to_datetime(news['Next Release']).dt.tz_localize(moscow_tz)

In [95]:
news['Next Release Days'] = news['Next Release'] - news['utc_dt']
news['Next Release Days (Days)'] = news['Next Release Days'].dt.days
news['Next Release Days (Hours)'] = news['Next Release Days'].dt.total_seconds() / 3600

In [99]:
news.head()

,DateTime,Currency,Impact,Event,Actual,Forecast,Previous,Detail,Next Release,Source,...,class,event_type,is_key_event,event_weight,utc_dt,event_time,custom_event_time,Next Release Days,Next Release Days (Days),Next Release Days (Hours)
0,2007-01-01T04:30:00+03:30,CNY,High Impact Expected,Manufacturing PMI,54.8,NaN,55.3,Source: CFLP (latest release) | Measures: Leve...,2007-02-01 00:00:00+03:00,CFLP (latest release),...,ECONOMIC_ACTIVITY,PMI_MANUFACTURING,True,3,2007-01-01 04:00:00+03:00,2007-01-01 04:00:00+03:00,2007-01-01 04:00:00+03:00,30 days 20:00:00,30.0,740.000000
1,2007-01-01T23:59:59+03:30,CAD,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: Canadian banks will be closed in ...,2007-04-06 00:00:00+04:00,None,...,OTHER,OTHER,False,1,2007-01-01 23:29:59+03:00,2007-01-01 23:00:00+03:00,2007-01-01 23:30:00+03:00,93 days 23:30:01,93.0,2255.500278
2,2007-01-01T23:59:59+03:30,USD,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: US banks will be closed in observ...,2007-01-15 00:00:00+03:00,None,...,OTHER,OTHER,False,1,2007-01-01 23:29:59+03:00,2007-01-01 23:00:00+03:00,2007-01-01 23:30:00+03:00,13 days 00:30:01,13.0,312.500278
3,2007-01-01T23:59:59+03:30,CNY,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: Chinese banks will be closed in o...,2007-01-02 00:00:00+03:00,None,...,OTHER,OTHER,False,1,2007-01-01 23:29:59+03:00,2007-01-01 23:00:00+03:00,2007-01-01 23:30:00+03:00,0 days 00:30:01,0.0,0.500278
4,2007-01-01T23:59:59+03:30,EUR,Non-Economic,German Bank Holiday,NaN,NaN,NaN,FF Notice: The European Central Bank's Trans-E...,2007-04-06 00:00:00+04:00,None,...,OTHER,OTHER,False,1,2007-01-01 23:29:59+03:00,2007-01-01 23:00:00+03:00,2007-01-01 23:30:00+03:00,93 days 23:30:01,93.0,2255.500278

In [47]:
for col in main_details:
    print(f'======== {col} ========')
    display(news[col].value_counts()[:10])

======== Next Release ========

Next Release
Feb 15, 2024     45
Dec 16, 2021     45
Aug 15, 2024     43
Nov 15, 2024     43
Dec 14, 2017     43
Mar 1, 2012      42
Mar 1, 2017      42
Apr 28, 2017     42
Dec 16, 2020     42
Mar 1, 2019      42
Name: count, dtype: int64

======== Source ========

Source
S&P Global (latest release)                          6019
Statistics Canada (latest release)                   4010
Office for National Statistics (latest release)      3808
Bank of England (latest release)                     3255
Federal Reserve (latest release)                     3051
Census Bureau (latest release)                       2625
Bureau of Labor Statistics (latest release)          2557
Eurostat (latest release)                            2497
Bank of Japan (latest release)                       2380
Australian Bureau of Statistics (latest release)     2175
Name: count, dtype: int64

======== Usual Effect ========

Usual Effect
'Actual' greater than 'Forecast' is good for currency;                          57430
More hawkish than expected is good for currency;                                11629
'Actual' less than 'Forecast' is good for currency;                              7158
Low liquidity and irregular volatility;                                          2141
No consistent effect - there are both risk and growth implications;              2076
No consistent effect - there are both inflationary and growth implications;        14
Name: count, dtype: int64

======== Frequency ========

Frequency
Released monthly, about 30 days after the month ends;                 4069
Released monthly, about 35 days after the month ends;                 3515
Released monthly, about 16 days after the month ends;                 3199
Released monthly, about 45 days after the month ends;                 3009
Released monthly, about 40 days after the month ends;                 3008
Released monthly, on the first business day after the month ends;     2902
Released monthly, around 3 weeks into the current month;              2885
Released monthly, on the third business day after the month ends;     2088
Scheduled 8 times per year;                                           1867
Released monthly, about 13 days after the month ends;                 1668
Name: count, dtype: int64

======== FF Notes ========

FF Notes
Most Forex brokers remain open for every holiday except Christmas and New Year's Day. Stock markets and banks have slightly different holiday schedules;                                                                                                                                                                                                                                                    2141
Auction results are reported in an 'X.XX                                                                                                                                                                                                                                                                                                                                                                    1856
Above 50.0 indicates industry expansion, below indicates contraction;                                                                                                                                                                                                                                                                                                                                       1540
Inventories are used to maintain price stability during supply shortages and periods of increasing demand;                                                                                                                                                                                                                                                                                                   953
While this is a US indicator, it most affects the loonie due to Canada's sizable energy sector;                                                                                                                                                                                                                                                                                                              952
This is the nation's earliest economic data. The market impact fluctuates from week to week - there tends to be more focus on the release when traders need to diagnose recent developments, or when the reading is at extremes;                                                                                                                                                                             952
While this is monthly data, it's reported in an annualized format (monthly figure x12);                                                                                                                                                                                                                                                                                                                      876
Above 50.0 indicates industry expansion, below indicates contraction. There are 2 versions of this report released about a week apart – Flash and Final. The Flash release, which the source first reported in Mar 2008, is the earliest and thus tends to have the most impact;                                                                                                                             820
Above 50.0 indicates industry expansion, below indicates contraction. The 'Previous' listed is the 'Actual' from the Flash release and therefore the 'History' data will appear unconnected. There are 2 versions of this report released about a week apart – Flash and Final. The Flash release, which the source first reported in Mar 2008, is the earliest and thus tends to have the most impact;      820
This is vital economic data released shortly after the month ends. The combination of importance and earliness makes for hefty market impacts;                                                                                                                                                                                                                                                               659
Name: count, dtype: int64

======== Why Traders Care ========

Why Traders Care
It's a leading indicator of economic health - businesses react quickly to market conditions, and their purchasing managers hold perhaps the most current and relevant insight into the company's view of the economy;                                                                                                  7197
Consumer prices account for a majority of overall inflation. Inflation is important to currency valuation because rising prices lead the central bank to raise interest rates out of respect for their inflation containment mandate;                                                                                  3168
Banks facilitate the majority of foreign exchange volume. When they are closed the market is less liquid and speculators become a more dominant market influence. This can lead to both abnormally low and abnormally high volatility;                                                                                 2141
Yields are set by bond market investors, and therefore they can be used to decipher investors' outlook on future interest rates. The bid-to-cover ratio represents bond market liquidity and demand, which can be used to gauge investor confidence;                                                                   2076
Financial confidence is a leading indicator of consumer spending, which accounts for a majority of overall economic activity;                                                                                                                                                                                          1979
It's a leading indicator of economic health - businesses react quickly to market conditions, and changes in their sentiment can be an early signal of future economic activity such as spending, hiring, and investment;                                                                                               1891
Export demand and currency demand are directly linked because foreigners must buy the domestic currency to pay for the nation's exports. Export demand also impacts production and prices at domestic manufacturers;                                                                                                   1887
Although it's generally viewed as a lagging indicator, the number of unemployed people is an important signal of overall economic health because consumer spending is highly correlated with labor-market conditions. Unemployment is also a major consideration for those steering the country's monetary policy;     1687
Federal Reserve FOMC members vote on where to set the nation's key interest rates and their public engagements are often used to drop subtle clues regarding future monetary policy;                                                                                                                                   1685
It's the broadest measure of economic activity and the primary gauge of the economy's health;                                                                                                                                                                                                                          1583
Name: count, dtype: int64

======== Measures ========

Measures
Level of a diffusion index based on surveyed purchasing managers in the manufacturing industry;                      3821
Change in the price of goods and services purchased by consumers;                                                    3308
Level of a diffusion index based on surveyed purchasing managers in the services industry;                           2898
Difference in value between imported and exported goods during the reported month;                                   2105
Change in the total inflation-adjusted value of output produced by manufacturers, mines, and utilities;              1975
Percentage of the total work force that is unemployed and actively seeking employment during the previous month;     1502
Change in the inflation-adjusted value of all goods and services produced by the economy;                            1461
Change in the total value of sales at the retail level;                                                              1347
Average yield on 10-year bonds the government sold at auction, and the bid-to-cover ratio of the auction;            1266
Change in the number of cubic feet of natural gas held in underground storage during the past week;                   953
Name: count, dtype: int64

======== Acro Expand ========

Acro Expand
Purchasing Managers' Index (PMI);           6538
Consumer Price Index (CPI);                 4917
Federal Open Market Committee (FOMC);       2196
Gross Domestic Product (GDP);               2123
Energy Information Administration (EIA);    1905
Producer Price Index (PPI);                 1751
Bank of Japan (BOJ);                        1448
European Central Bank (ECB);                1410
Reserve Bank of Australia (RBA);            1384
Bank of Canada (BOC);                       1106
Name: count, dtype: int64

======== Also Called ========

Also Called
Jobless Rate;                                         1578
Industrial Output;                                    1078
Nat Gas Stocks, Nat Gas Inventories, Working Gas;      953
Jobless Claims, Initial Claims;                        952
Crude Stocks, Crude Levels;                            952
Leading Indicators;                                    836
Interest Rate Statement;                               625
Retail Sales Ex Autos;                                 561
Import Price Index;                                    511
Interest Rates;                                        502
Name: count, dtype: int64

======== Derived Via ========

Derived Via
Survey of about 400 purchasing managers which asks respondents to rate the relative level of business conditions including employment, production, new orders, prices, supplier deliveries, and inventories;                      2427
The average price of various goods and services are sampled and then compared to the previous sampling;                                                                                                                           1353
Survey of about 650 purchasing managers which asks respondents to rate the relative level of business conditions including employment, production, new orders, prices, supplier deliveries, and inventories;                       738
Survey of about 800 purchasing managers which asks respondents to rate the relative level of business conditions including employment, production, new orders, prices, supplier deliveries, and inventories;                       720
Survey of about 300 purchasing managers which asks respondents to rate the relative level of business conditions including employment, production, new orders, prices, supplier deliveries, and inventories;                       440
The average price of various goods and services are sampled and then compared to the sampling done a year earlier;                                                                                                                 438
Survey of about 5,000 purchasing managers which asks respondents to rate the relative level of business conditions including employment, production, new orders, prices, supplier deliveries, and inventories;                     428
Survey of about 750 purchasing managers which asks respondents to rate the relative level of business conditions including employment, production, new orders, prices, supplier deliveries, and inventories;                       410
The weighted-average price of the 9 dairy products sold at auction are sampled and then compared to the previous sampling;                                                                                                         378
Survey of about 2,000 consumers which asks respondents to rate the relative level of past and future economic conditions, including personal financial situation, climate for major purchases, and overall economic situation;     225
Name: count, dtype: int64

======== Description ========

Description
Chinese banks will be closed in observance of the Spring Festival;                                                           95
Chinese banks will be closed in observance of National Day;                                                                  83
Japanese banks will be closed in observance of the 4-day Bank Holiday;                                                       53
Due to hold a press conference, along with other MPC members, about the Inflation Report, in London;                         50
Due to hold a press conference about the coronavirus, in Washington DC;                                                      38
Chinese banks will be closed in observance of Labor Day;                                                                     34
Due to testify on the Semiannual Monetary Policy Report before the House Financial Services Committee, in Washington DC;     29
Due to testify on the Semiannual Monetary Policy Report before the Senate Banking Committee, in Washington DC;               28
Chinese banks will be closed in observance of Tomb Sweeping Day;                                                             28
Chinese banks will be closed in observance of the Dragon Boat Festival;                                                      27
Name: count, dtype: int64

======== Speaker ========

Speaker
ECB President Jean-Claude Trichet;                             246
Federal Reserve Chairman Ben Bernanke;                         239
ECB President Christine Lagarde;                               223
Federal Reserve Bank of New York President John Williams;      218
BOJ Governor;                                                  203
ECB President Mario Draghi;                                    203
ECB President and Vice President;                              178
BOE Governor Mark Carney;                                      166
Federal Reserve Bank of New York President William Dudley;     162
Federal Reserve Chair Jerome Powell;                           159
Name: count, dtype: int64

======== FF Notice ========

FF Notice
Source released data 1 minute earlier than scheduled;                                                                                                                                                        438
Source released data 2 minutes later than scheduled;                                                                                                                                                         379
The European Central Bank's Trans-European Automated Real-time Gross Settlement Express Transfer (TARGET) system will be closed for this holiday, which tends to have a substantial impact on liquidity;     222
Source released data 2 minutes earlier than scheduled;                                                                                                                                                       221
For historical accuracy, this event was added to the calendar after its release time;                                                                                                                        171
Source released data 3 minutes later than scheduled;                                                                                                                                                         156
Text of the speech due to be released 15 minutes earlier than the speaking time listed;                                                                                                                       93
Initial release time was shifted 24 hours later due to source rescheduling;                                                                                                                                   90
Source released data 4 minutes later than scheduled;                                                                                                                                                          84
Source released data 5 minutes later than scheduled;                                                                                                                                                          70
Name: count, dtype: int64

### Standartize Actual, Forecast and Previous values

In [48]:
def standardize_economic_value(value):
    """
    Standardize economic indicator values from news data.
    Handles:
    - Numeric strings (e.g., '54.8', '55.3')
    - Percentages (e.g., '2.5%', '-1.2%')
    - Strings with units or text
    - NaN/None values
    - Empty strings
    
    Returns: float or np.nan
    """
    if pd.isna(value) or value == '' or value is None:
        return np.nan
    
    # Convert to string if not already
    value_str = str(value).strip()
    
    # Remove common prefixes/suffixes and clean
    value_str = value_str.replace(',', '')  # Remove thousand separators
    value_str = value_str.replace('$', '')   # Remove dollar signs
    value_str = value_str.replace('€', '')   # Remove euro signs
    value_str = value_str.replace('£', '')  # Remove pound signs
    
    # Handle percentages
    if '%' in value_str:
        value_str = value_str.replace('%', '')
        try:
            return float(value_str) / 100.0  # Convert percentage to decimal
        except (ValueError, TypeError):
            return np.nan
    
    # Try to convert to float directly
    try:
        return float(value_str)
    except (ValueError, TypeError):
        # If conversion fails, try to extract number from string
        import re
        # Extract first number found in the string
        numbers = re.findall(r'-?\d+\.?\d*', value_str)
        if numbers:
            try:
                return float(numbers[0])
            except (ValueError, TypeError):
                return np.nan
        return np.nan

In [49]:
# Standardize the columns
news['Actual_norm'] = news['Actual'].apply(standardize_economic_value)
news['Forecast_norm'] = news['Forecast'].apply(standardize_economic_value)
news['Previous_norm'] = news['Previous'].apply(standardize_economic_value)

In [50]:
news.tail()

,DateTime,Currency,Impact,Event,Actual,Forecast,Previous,Detail,Next Release,Source,...,Acro Expand,Also Called,Derived Via,Description,Speaker,FF Notice,Source2,Actual_norm,Forecast_norm,Previous_norm
83422,2025-04-07T10:30:00+04:30,CHF,Low Impact Expected,Foreign Currency Reserves,NaN,NaN,735B,Source: Swiss National Bank (latest release) |...,"May 7, 2025",Swiss National Bank (latest release),...,Swiss National Bank (SNB);,None,None,None,None,None,Swiss National Bank,NaN,NaN,735.000
83423,2025-04-07T12:00:00+04:30,EUR,Low Impact Expected,Sentix Investor Confidence,NaN,-8.9,-2.9,Source: Sentix (latest release) | Measures: Le...,"May 5, 2025",Sentix (latest release),...,None,None,"Survey of about 6,600 investors and analysts w...",None,None,None,Sentix,NaN,-8.900,-2.900
83424,2025-04-07T12:30:00+04:30,EUR,Low Impact Expected,Retail Sales m/m,NaN,0.5%,-0.3%,Source: Eurostat (latest release) | Measures: ...,"May 7, 2025",Eurostat (latest release),...,None,None,None,None,None,None,Eurostat,NaN,0.005,-0.003
83425,2025-04-07T18:00:00+04:30,CAD,Low Impact Expected,BOC Business Outlook Survey,NaN,NaN,NaN,Source: Bank of Canada (latest release) | Usua...,"Jul 21, 2025",Bank of Canada (latest release),...,Bank of Canada (BOC);,Senior Loan Officer Survey;,"Survey of about 1,000 businesses which asks re...",None,None,None,Bank of Canada,NaN,NaN,NaN
83426,2025-04-07T22:30:00+04:30,USD,Low Impact Expected,Consumer Credit m/m,NaN,15.2B,18.1B,Source: Federal Reserve (latest release) | Mea...,"May 7, 2025",Federal Reserve (latest release),...,None,None,None,None,None,None,Federal Reserve,NaN,15.200,18.100

### Установка ранга для поля Impact

In [51]:
def set_rank_for_impact(impact: str):
    if impact == 'High Impact Expected':
        return 3
    elif impact == 'Medium Impact Expected':
        return 2
    elif impact == 'Low Impact Expected':
        return 1
    else:
        return 0

In [52]:
news['impact_rank'] = news['Impact'].apply(set_rank_for_impact)

### Классификация новостей по группам

In [53]:
NEWS_CLASSES = [
    "MONETARY_POLICY",      # решения ЦБ
    "CB_SPEECH",            # речи ЦБ
    "INFLATION",            # инфляция
    "LABOR_MARKET",         # рынок труда
    "ECONOMIC_ACTIVITY",    # рост / производство
    "SENTIMENT",            # опросы / ожидания
    "CONSUMER_HOUSING",     # потребитель / жильё
    "TRADE_FINANCE",        # торговля / деньги / финансы
    "COMMODITIES"           # нефть / газ / сырьё
]

In [54]:
MONETARY_POLICY = [
    "rate", "policy", "monetary", "fomc", "mpc", "meeting",
    "minutes", "statement", "votes",
    "asset purchase", "purchase facility", "refinancing",
    "cash rate", "bank rate", "official cash",
    "fed", "ecb", "boe", "boj", "rba", "rbnz", "boc", "snb",
    "overnight rate", "federal funds", "funds rate"
]

CB_SPEECH = [
    "speaks", "press conference", "press",
    "chair", "president", "gov",
    "powell", "lagarde", "bailey", "kuroda", "draghi",
    "yellen", "carney", "bullard", "waller", "kashkari",
    "member"
]

INFLATION = [
    "cpi", "core cpi", "ppi", "core ppi",
    "pce", "core pce",
    "inflation", "price index", "prices",
    "median cpi", "trimmed cpi",
    "inflation expectations"
]

LABOR_MARKET = [
    "employment", "unemployment", "job", "claims",
    "non farm", "nonfarm", "payrolls",
    "adp", "jolts", "job openings",
    "earnings", "hourly earnings",
    "job cuts", "challenger"
]

ECONOMIC_ACTIVITY = [
    "gdp", "industrial", "production",
    "manufacturing", "services",
    "orders", "factory orders",
    "output", "capacity", "utilization",
    "productivity", "investment"
]

SENTIMENT = [
    "pmi", "ism", "confidence", "sentiment",
    "ifo", "zew", "gfk", "nfib", "philly",
    "survey", "optimism", "barometer",
    "expectations", "watchers"
]

CONSUMER_HOUSING = [
    "retail", "sales", "consumer",
    "housing", "home", "mortgage",
    "building", "permits", "starts",
    "house price", "hpi"
]

TRADE_FINANCE = [
    "trade", "balance", "current account",
    "budget", "borrowing", "credit",
    "money supply", "m2", "m3",
    "lending", "loans", "reserves",
    "foreign", "currency"
]

COMMODITIES = [
    "oil", "crude", "gas",
    "inventories", "storage",
    "opec", "commodity prices"
]

In [55]:
CLASS_KEYWORDS = {
    "MONETARY_POLICY": MONETARY_POLICY,
    "CB_SPEECH": CB_SPEECH,
    "INFLATION": INFLATION,
    "LABOR_MARKET": LABOR_MARKET,
    "ECONOMIC_ACTIVITY": ECONOMIC_ACTIVITY,
    "SENTIMENT": SENTIMENT,
    "CONSUMER_HOUSING": CONSUMER_HOUSING,
    "TRADE_FINANCE": TRADE_FINANCE,
    "COMMODITIES": COMMODITIES
}

In [57]:
def classify_news(title: str):
    title = title.lower()
    scores = {}

    for cls, keywords in CLASS_KEYWORDS.items():
        scores[cls] = sum(1 for k in keywords if k in title)

    if max(scores.values()) == 0:
        return "OTHER"

    return max(scores, key=scores.get)

In [58]:
news['class'] = news['Event'].astype(str).apply(classify_news)

### Добавление категорий отдельных новостей, важности новости и ее веса

In [59]:
def detect_event_type(title: str) -> str:
    t = title.lower()

    if "non farm" in t or "nonfarm" in t:
        return "NFP"
    if "cpi" in t and "core" in t:
        return "CORE_CPI"
    if "cpi" in t:
        return "CPI"
    if "pce" in t:
        return "PCE"
    if "fomc" in t and "rate" in t:
        return "FOMC_RATE"
    if "fomc" in t and "press" in t:
        return "FOMC_PRES_CONF"
    if "pmi" in t and "manufacturing" in t:
        return "PMI_MANUFACTURING"  # TODO: Check this line
    if "pmi" in t and "services" in t:
        return "PMI_SERVICES"
    if "gdp" in t:
        return "GDP"
    if "retail" in t:
        return "RETAIL_SALES"

    return "OTHER"

In [60]:
news["event_type"] = news['Event'].apply(detect_event_type)

In [61]:
KEY_EVENTS = {
    "NFP", "CPI", "CORE_CPI", "PCE",
    "FOMC_RATE", "FOMC_PRES_CONF",
    "PMI_MANUFACTURING", "PMI_SERVICES",
    "GDP"
}

news["is_key_event"] = news["event_type"].isin(KEY_EVENTS)

In [62]:
EVENT_WEIGHTS = {
    "NFP": 5,
    "CPI": 5,
    "CORE_CPI": 5,
    "PCE": 4,
    "FOMC_RATE": 5,
    "FOMC_PRES_CONF": 4,
    "PMI_MANUFACTURING": 3,
    "PMI_SERVICES": 3,
    "GDP": 3,
    "RETAIL_SALES": 2,
    "OTHER": 1
}

news["event_weight"] = news["event_type"].map(EVENT_WEIGHTS)

In [63]:
news.head(3)

,DateTime,Currency,Impact,Event,Actual,Forecast,Previous,Detail,Next Release,Source,...,Previous_norm,impact_rank,detail_description,detail_usual_effect,detail_next_release,detail_why_traders_care,class,event_type,is_key_event,event_weight
0,2007-01-01T04:30:00+03:30,CNY,High Impact Expected,Manufacturing PMI,54.8,NaN,55.3,Source: CFLP (latest release) | Measures: Leve...,"Feb 1, 2007",CFLP (latest release),...,55.3,3,None,'Actual' greater than 'Forecast' is good for c...,"Feb 1, 2007",It's a leading indicator of economic health - ...,ECONOMIC_ACTIVITY,PMI_MANUFACTURING,True,3
1,2007-01-01T23:59:59+03:30,CAD,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: Canadian banks will be closed in ...,"Apr 6, 2007",None,...,NaN,0,Canadian banks will be closed in observance of...,Low liquidity and irregular volatility,"Apr 6, 2007",Banks facilitate the majority of foreign excha...,OTHER,OTHER,False,1
2,2007-01-01T23:59:59+03:30,USD,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: US banks will be closed in observ...,"Jan 15, 2007",None,...,NaN,0,US banks will be closed in observance of New Y...,Low liquidity and irregular volatility,"Jan 15, 2007",Banks facilitate the majority of foreign excha...,OTHER,OTHER,False,1

### Построение агрегированных новостей для МЛ модели

In [64]:
news['utc_dt'] = pd.to_datetime(news['DateTime'], utc=True).dt.tz_convert(moscow_tz)
# news['event_hour'] = news['utc_dt'].dt.ceil('H', ambiguous='NaT', nonexistent='shift_forward')
news['event_time'] = news['utc_dt'].dt.floor('30min')

In [65]:
def floor_or_ceil(x: str):
    x_dt = pd.to_datetime(x)
    if (29 >= x_dt.minute >= 20) or (59 >= x_dt.minute >= 50):  # TODO: May be change to last 5 minutes (20 -> 25 and 50 -> 55)
        return x_dt.ceil('30min', ambiguous='NaT', nonexistent='shift_forward')
    else:
        return x_dt.floor('30min')

In [66]:
news['custom_event_time'] = news['utc_dt'].progress_apply(floor_or_ceil)

100%|██████████| 83427/83427 [00:05<00:00, 15572.15it/s]

In [67]:
def build_hour_features(
    news_df: pd.DataFrame,
    key_event_types: list[str] | None = None,
    event_time_column: str = 'custom_event_time'
) -> pd.DataFrame:
    """
    Build hour-level aggregated features from event-level news dataframe.

    Parameters
    ----------
    news_df : pd.DataFrame
        Event-level news data. Must contain:
        ['event_hour', 'event_type', 'news_class',
         'impact_rank', 'is_key_event', 'event_weight']

    key_event_types : list[str], optional
        List of key event types to build presence flags for
        (e.g. ['NFP', 'CPI', 'PMI_MANUFACTURING']).
        If None, inferred from is_key_event == True.

    Returns
    -------
    pd.DataFrame
        Hour-level feature table indexed by event_hour.
    """

    df = news_df.copy()

    # -----------------------------
    # 1. BASIC COUNTS & INTENSITY
    # -----------------------------
    agg = df.groupby(event_time_column).agg(
        news_count=("event_type", "count"),
        high_impact_count=("impact_rank", lambda x: (x == 3).sum()),
        key_event_count=("is_key_event", "sum"),
        sum_impact=("impact_rank", "sum"),
        sum_event_weight=("event_weight", "sum"),
        max_event_weight=("event_weight", "max"),
    )

    # -----------------------------
    # 2. DOMINANT EVENT TYPE
    # -----------------------------
    dominant_event = (
        df.groupby([event_time_column, "event_type"])
          .size()
          .reset_index(name="cnt")
          .sort_values([event_time_column, "cnt"], ascending=[True, False])
          .drop_duplicates(event_time_column)
          .set_index(event_time_column)[["event_type"]]
          .rename(columns={"event_type": "dominant_event_type"})
    )

    # -----------------------------
    # 3. EVENT ENTROPY (STRUCTURAL NOISE)
    # -----------------------------
    def event_entropy(x: pd.Series) -> float:
        probs = x.value_counts(normalize=True)
        return entropy(probs) if len(probs) > 1 else 0.0

    entropy_df = (
        df.groupby(event_time_column)["event_type"]
          .apply(event_entropy)
          .to_frame("event_entropy")
    )

    # -----------------------------
    # 4. KEY EVENT PRESENCE FLAGS
    # -----------------------------
    if key_event_types is None:
        key_event_types = (
            df.loc[df["is_key_event"], "event_type"]
              .dropna()
              .unique()
              .tolist()
        )

    presence_flags = []
    for evt in key_event_types:
        s = (
            df[df["event_type"] == evt]
            .groupby(event_time_column)
            .size()
            .rename(f"has_{evt.lower()}")
        )
        presence_flags.append(s)

    presence_df = (
        pd.concat(presence_flags, axis=1)
        .fillna(0)
        .astype(int)
    ) if presence_flags else pd.DataFrame(index=agg.index)

    # -----------------------------
    # 5. FINAL MERGE
    # -----------------------------
    hour_features = (
        agg
        .join(dominant_event, how="left")
        .join(entropy_df, how="left")
        .join(presence_df, how="left")
        .reset_index()
    )

    # Fill NaNs (safety)
    num_cols = hour_features.select_dtypes(include=[np.number]).columns
    hour_features[num_cols] = hour_features[num_cols].fillna(0)

    hour_features["dominant_event_type"] = (
        hour_features["dominant_event_type"]
        .fillna("NONE")
        .astype("category")
    )

    # Create field 'Last_key_event_bars_ago' (example last important event was N bars ago and it was NFP)
    # Find last key event name and how many hours ago it was for each hour row

    # Prepare a mask for rows with actual key events (using is_key_event)
    key_event_mask = hour_features['dominant_event_type'].isin(key_event_types)

    # Build up last key event name using a forward fill
    hour_features['last_key_event_name'] = (
        hour_features['dominant_event_type'].where(key_event_mask).shift(1)
        .ffill()
    )

    # For time calculations, get event_hour of previous key events
    last_key_event_time = hour_features[event_time_column].where(key_event_mask).shift(1).ffill()

    hour_features['last_key_event_hours_ago'] = (
        (hour_features[event_time_column] - last_key_event_time).dt.total_seconds() / 3600
    )

    return hour_features

In [68]:
news_agg = build_hour_features(news, key_event_types=KEY_EVENTS)

In [69]:
news_agg.sample(5)

,custom_event_time,news_count,high_impact_count,key_event_count,sum_impact,sum_event_weight,max_event_weight,dominant_event_type,event_entropy,has_core_cpi,has_nfp,has_pmi_services,has_cpi,has_fomc_pres_conf,has_pce,has_fomc_rate,has_gdp,has_pmi_manufacturing,last_key_event_name,last_key_event_hours_ago
8826,2009-12-21 13:00:00+03:00,1,0,0,1,1,1,OTHER,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CORE_CPI,94.0
31903,2017-08-29 09:30:00+03:00,1,0,0,1,1,1,OTHER,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CORE_CPI,1.5
45567,2022-03-08 03:30:00+03:00,1,0,0,1,1,1,OTHER,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,PMI_SERVICES,106.0
14430,2011-10-31 00:30:00+04:00,6,0,1,8,10,5,OTHER,0.450561,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,PCE,56.0
45956,2022-04-25 11:00:00+03:00,1,0,0,2,1,1,OTHER,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,PMI_MANUFACTURING,66.5

In [70]:
news_agg[['custom_event_time', 'dominant_event_type', 'last_key_event_name', 'last_key_event_hours_ago']].head(10)

,custom_event_time,dominant_event_type,last_key_event_name,last_key_event_hours_ago
0,2007-01-01 04:00:00+03:00,PMI_MANUFACTURING,NaN,NaN
1,2007-01-01 23:30:00+03:00,OTHER,PMI_MANUFACTURING,19.5
2,2007-01-02 01:30:00+03:00,OTHER,PMI_MANUFACTURING,21.5
3,2007-01-02 03:00:00+03:00,OTHER,PMI_MANUFACTURING,23.0
4,2007-01-02 05:30:00+03:00,PMI_MANUFACTURING,PMI_MANUFACTURING,25.5
5,2007-01-02 08:30:00+03:00,OTHER,PMI_MANUFACTURING,3.0
6,2007-01-02 11:00:00+03:00,PMI_MANUFACTURING,PMI_MANUFACTURING,5.5
7,2007-01-02 11:30:00+03:00,PMI_MANUFACTURING,PMI_MANUFACTURING,0.5
8,2007-01-02 12:00:00+03:00,PMI_MANUFACTURING,PMI_MANUFACTURING,0.5
9,2007-01-02 12:30:00+03:00,PMI_MANUFACTURING,PMI_MANUFACTURING,0.5

### TODO
сделать агрегацию новостей по часу с указанием:
- сколько новостей собралось в этом часу
- как давно была последняя новость
- как давно была важная новость
- (дальше с присоединением котировок)
- какие параметры у новости были тогда в момент выхода прошлой новости

In [43]:
news_agg['last_key_event_name'].value_counts()

last_key_event_name
CPI                  15788
GDP                  12280
PMI_MANUFACTURING     9656
CORE_CPI              8088
PMI_SERVICES          7895
PCE                    481
FOMC_PRES_CONF         477
NFP                    302
OTHER                    0
RETAIL_SALES             0
Name: count, dtype: int64

## Загрузка котировок

In [ ]:
# import MetaTrader5 as mt5
# import numpy as np
# import pandas as pd
# from datetime import datetime

In [ ]:
# def get_prices_from_mt5(ticker: str, tf=mt5.TIMEFRAME_D1, from_date: datetime = datetime(2010, 1, 1), till_date: datetime = datetime.now()):
#     # connect to MetaTrader 5
#     path_to_terminal = "C:\\Program Files\\AMarkets - MetaTrader 5\\terminal64.exe"
#     if not mt5.initialize(path=path_to_terminal):
#         print("initialize() failed")
#         mt5.shutdown()

#     rates = mt5.copy_rates_range(ticker, tf, from_date, till_date)
#     df = pd.DataFrame(rates)
#     df['time'] = pd.to_datetime(df['time'], unit='s')
#     df = df.drop(['real_volume'], axis=1)
#     for col in ['open', 'high', 'low', 'close']:
#         df[col] = df[col].apply(lambda x: np.round(x, 5))
#     return df

In [ ]:
# prices = get_prices_from_mt5('EURUSDb', mt5.TIMEFRAME_H1, from_date=datetime(2014, 1, 1), till_date=datetime(2025, 4, 10))

In [1]:
import os

In [ ]:
def read_pair(pair: str, path2folder: str = "..\\dataset\\fx_data\\"):
    return pd.read_csv('..\\dataset\\fx_data\\EURUSD_M30.csv',
                        sep="\t",
                        names=["time", "open", "high", "low", "close", "volume", "spread"],
                        header=0,
                        parse_dates=["time"])

In [65]:
prices = pd.read_csv('..\\dataset\\fx_data\\EURUSD_M30.csv',
    sep="\t",
    names=["time", "open", "high", "low", "close", "volume", "spread"],
    header=0,
    parse_dates=["time"])
prices.head()

                 time     open     high      low    close  volume  spread
0 2009-12-31 16:30:00  1.43989  1.44022  1.43706  1.43972    2045       9
1 2009-12-31 17:00:00  1.43977  1.44037  1.43817  1.43838    2203       9
2 2009-12-31 17:30:00  1.43831  1.43899  1.43612  1.43690    1903       9
3 2009-12-31 18:00:00  1.43669  1.43697  1.43154  1.43206    2148       9
4 2009-12-31 18:30:00  1.43189  1.43551  1.43025  1.43465    2080       8

In [67]:
prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199422 entries, 0 to 199421
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   time    199422 non-null  datetime64[ns]
 1   open    199422 non-null  float64
 2   high    199422 non-null  float64
 3   low     199422 non-null  float64
 4   close   199422 non-null  float64
 5   volume  199422 non-null  int64
 6   spread  199422 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(2)
memory usage: 10.7 MB

In [66]:
print('News min date: ', pd.to_datetime(prices['time']).min())
print('News max date: ', pd.to_datetime(prices['time']).max())

News min date:  2009-12-31 16:30:00
News max date:  2026-01-14 10:30:00

## Фичи для котировок

### Фичи для определения волатильности
- range efficiency
- directional noise index
- normalized rolling volume
- normalized rolling range

In [55]:
import talib as ta
from hurst import compute_Hc
from tqdm.auto import tqdm

tqdm.pandas(desc="Processing DataFrame")

In [56]:
PERIOD = 12

In [68]:
def kaufman_efficiency_ratio(data: pd.DataFrame, window: int):
    direction = data.close.diff().abs()
    sum_range = data.range.rolling(window).sum()
    return direction / sum_range

In [69]:
def custom_range_efficiency(data: pd.DataFrame, window: int = 3) -> float:
    """
    Calculates the range efficiency for a given window size on OHLC price data.
    
    Range efficiency is defined as the ratio of the total range (difference between
    highest high and lowest low over the window) to the sum of the ranges (high-low per bar)
    within that window. 
    Higher values indicate more directional movement within the window,
    while lower values indicate more choppy or noisy price action.
    """
    total_range = data.high.rolling(window).max() - data.low.rolling(window).min()
    sum_range = data.range.rolling(window=window).sum()
    return total_range / sum_range

In [70]:
def noise_inside_the_bars(data: pd.DataFrame):
    body = (data['open'] - data['close']).abs()
    bar_range = data['high'] - data['low']
    return (bar_range - body) / (body + 1e-9)

In [71]:
def relative_atr(data: pd.DataFrame, window: int):
    atr = ta.ATR(data['high'], data['low'], data['close'], window)
    return (atr - atr.rolling(window*5).mean()) / atr.rolling(window*5).std()

In [72]:
def get_bb_width(data: pd.DataFrame, window: int):
    upper_band, middle_band, lower_band = ta.BBANDS(
        data['close'], 
        timeperiod=window, 
        nbdevup=3,
        nbdevdn=3,
        matype=0
    )
    return upper_band - lower_band

In [73]:
def rolling_hurst(series: pd.Series, window=100):
    def get_h(sub_series):
        if len(sub_series) < 50:
            return np.nan
        H, _, _ = compute_Hc(sub_series, kind='price', simplified=True)
        return H
    
    return series.rolling(window=window).progress_apply(get_h, raw=False)

In [78]:
def calculate_chaos_features(data: pd.DataFrame, window: int = 14):
    data['range'] = ta.TRANGE(data['high'], data['low'], data['close'])

    # 1. Kaufman Efficiency Ratio
    data['kaufman_efficiency_ratio'] = kaufman_efficiency_ratio(data, window=window)

    # 2. Custom Range efficiency
    data['custom_range_efficiency'] = custom_range_efficiency(data, window=window)

    # 3. Wick-to-Body Ratio (Шум внутри баров)
    data['wick_ratio'] = noise_inside_the_bars(data)

    # 4. Relative ATR
    data['relative_atr'] = relative_atr(data, window=window)

    # 5. BB width
    data['bb_width'] = get_bb_width(data, window=window)

    # 6. Anomaly volume
    v_mean = data['volume'].rolling(window*5).mean()
    v_std = data['volume'].rolling(window*5).std()
    data['volume_zscore'] = (data['volume'] - v_mean) / (v_std + 1e-9)

    # 7. Price to Volume
    data['price_volume_ratio'] = data.range / (data.volume + 1e-9)

    # 8. Hurst Exponent
    data['hurst'] = rolling_hurst(data['close'], window=100)
    
    return data

In [79]:
prices = calculate_chaos_features(prices, window=PERIOD)

Processing DataFrame: 199323it [01:54, 1745.01it/s]

In [83]:
def label_future_chaos(data: pd.DataFrame, N=5, stop_mult=1.5, neutral_threshold: float = 0.3):
    """
    Генерирует сигналы о будущем хаосе на N баров вперед.
    stop_mult: множитель ATR для определения "выноса стопов"
    """
    atr = ta.ATR(data['high'], data['low'], data['close'], N*3)
    
    # Future min/max values
    future_max = data['high'].shift(-N).rolling(N).max()
    future_min = data['low'].shift(-N).rolling(N).min()
    future_range = future_max - future_min
    future_close = data['close'].shift(-N)
    current_close = data['close']

    # Find stop levels
    upper_stop = current_close + (atr * stop_mult)
    lower_stop = current_close - (atr * stop_mult)

    # Targets
    target_volatility_expantion = future_range > (atr * 3)
    target_whipsaw = (future_max > upper_stop) & (future_min < lower_stop)
    target_chaos = target_volatility_expantion | target_whipsaw

    # Return close price to open
    returned = abs(future_close - current_close) < (atr * neutral_threshold)
    target_neutral_chaos = (target_whipsaw & returned).astype(int)
    target_strong_move = (target_whipsaw & ~returned).astype(int)

    # data['target_whipsaw'] = target_whipsaw
    data['target_volatility_expantion'] = target_volatility_expantion.astype(int)
    data['target_chaos'] = target_chaos.astype(int)
    data['target_neutral_chaos'] = target_neutral_chaos
    data['target_strong_move'] = target_strong_move

    return data

In [84]:
prices = label_future_chaos(prices, N=12)

In [85]:
prices.sample(5)

,time,open,high,low,close,volume,spread,range,kaufman_efficiency_ratio,custom_range_efficiency,wick_ratio,relative_atr,bb_width,volume_zscore,price_volume_ratio,hurst,target_volatility_expantion,target_chaos,target_neutral_chaos,target_strong_move
158782,2022-10-06 05:00:00,0.99105,0.99181,0.99061,0.99091,12415,6,0.00120,0.011696,0.444444,7.571374,-0.855597,0.008514,0.359102,9.665727e-08,0.675524,1,1,0,0
34902,2012-10-17 17:30:00,1.31242,1.31282,1.31176,1.31211,7441,5,0.00106,0.016885,0.232571,2.419347,0.656491,0.004476,1.251011,1.424540e-07,0.770749,0,0,0,0
192086,2025-06-11 14:00:00,1.14383,1.14404,1.14281,1.14297,1725,4,0.00123,0.063150,0.300892,0.430232,-0.296985,0.006310,-0.493799,7.130435e-07,0.377824,1,1,0,0
38956,2013-02-14 18:00:00,1.33425,1.33445,1.33196,1.33424,6471,5,0.00249,0.000431,0.293966,247.975202,1.046595,0.005900,1.314921,3.847937e-07,0.690175,0,0,0,0
132317,2020-08-20 19:30:00,1.18564,1.18589,1.18526,1.18541,5137,3,0.00063,0.011917,0.314796,1.739123,0.707816,0.007882,-0.391761,1.226397e-07,0.666390,0,0,0,0

## Присоединение к котировочным фичам новостные фичи

In [86]:
prices.head()

,time,open,high,low,close,volume,spread,range,kaufman_efficiency_ratio,custom_range_efficiency,wick_ratio,relative_atr,bb_width,volume_zscore,price_volume_ratio,hurst,target_volatility_expantion,target_chaos,target_neutral_chaos,target_strong_move
0,2009-12-31 16:30:00,1.43989,1.44022,1.43706,1.43972,2045,9,NaN,NaN,NaN,17.588132,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1,2009-12-31 17:00:00,1.43977,1.44037,1.43817,1.43838,2203,9,0.00220,NaN,NaN,0.582733,NaN,NaN,NaN,9.986382e-07,NaN,0,0,0,0
2,2009-12-31 17:30:00,1.43831,1.43899,1.43612,1.43690,1903,9,0.00287,NaN,NaN,1.035460,NaN,NaN,NaN,1.508145e-06,NaN,0,0,0,0
3,2009-12-31 18:00:00,1.43669,1.43697,1.43154,1.43206,2148,9,0.00543,NaN,NaN,0.172786,NaN,NaN,NaN,2.527933e-06,NaN,0,0,0,0
4,2009-12-31 18:30:00,1.43189,1.43551,1.43025,1.43465,2080,8,0.00526,NaN,NaN,0.905797,NaN,NaN,NaN,2.528846e-06,NaN,0,0,0,0

In [87]:
prices['utc_dt'] = pd.to_datetime(prices['time']).dt.tz_localize(moscow_tz)

In [92]:
df = prices.merge(news_agg, how='left', left_on='utc_dt', right_on='custom_event_time').dropna()

In [93]:
df.head()

,time,open,high,low,close,volume,spread,range,kaufman_efficiency_ratio,custom_range_efficiency,...,has_cpi,has_fomc_pres_conf,has_nfp,has_gdp,has_fomc_rate,has_pmi_services,has_core_cpi,has_pmi_manufacturing,last_key_event_name,last_key_event_hours_ago
103,2010-01-04 21:00:00,1.44127,1.44221,1.44105,1.44199,1195,9,0.00116,0.019868,0.248519,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,PMI_MANUFACTURING,3.0
108,2010-01-04 23:30:00,1.44188,1.44215,1.44074,1.44105,1725,9,0.00141,0.032807,0.228821,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,PMI_MANUFACTURING,5.5
115,2010-01-05 03:00:00,1.44238,1.44395,1.44181,1.44253,635,9,0.00214,0.004992,0.218525,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,PMI_MANUFACTURING,9.0
131,2010-01-05 11:00:00,1.44508,1.44535,1.44183,1.44250,2112,9,0.00352,0.095450,0.293378,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,PMI_MANUFACTURING,17.0
133,2010-01-05 12:00:00,1.44191,1.44368,1.44126,1.44274,2017,8,0.00242,0.035064,0.275696,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,PMI_MANUFACTURING,18.0

In [100]:
def add_time_feaures(data: pd.DataFrame, dt_col: str):
    data[dt_col] = pd.to_datetime(data[dt_col])
    data['quarter'] = data[dt_col].dt.quarter
    data['week'] = data[dt_col].dt.isocalendar().week
    data['dayofweek'] = data[dt_col].dt.dayofweek
    data['day'] = data[dt_col].dt.day
    data['hour'] = data[dt_col].dt.hour
    data['minute'] = data[dt_col].dt.minute
    return data

In [101]:
df = add_time_feaures(df, 'time')

In [102]:
df.head()

,time,open,high,low,close,volume,spread,range,kaufman_efficiency_ratio,custom_range_efficiency,...,has_core_cpi,has_pmi_manufacturing,last_key_event_name,last_key_event_hours_ago,quarter,week,dayofweek,day,hour,minute
103,2010-01-04 21:00:00,1.44127,1.44221,1.44105,1.44199,1195,9,0.00116,0.019868,0.248519,...,0.0,0.0,PMI_MANUFACTURING,3.0,1,1,0,4,21,0
108,2010-01-04 23:30:00,1.44188,1.44215,1.44074,1.44105,1725,9,0.00141,0.032807,0.228821,...,0.0,0.0,PMI_MANUFACTURING,5.5,1,1,0,4,23,30
115,2010-01-05 03:00:00,1.44238,1.44395,1.44181,1.44253,635,9,0.00214,0.004992,0.218525,...,0.0,0.0,PMI_MANUFACTURING,9.0,1,1,1,5,3,0
131,2010-01-05 11:00:00,1.44508,1.44535,1.44183,1.44250,2112,9,0.00352,0.095450,0.293378,...,0.0,0.0,PMI_MANUFACTURING,17.0,1,1,1,5,11,0
133,2010-01-05 12:00:00,1.44191,1.44368,1.44126,1.44274,2017,8,0.00242,0.035064,0.275696,...,0.0,0.0,PMI_MANUFACTURING,18.0,1,1,1,5,12,0

In [103]:
df.columns

Index(['time', 'open', 'high', 'low', 'close', 'volume', 'spread', 'range',
       'kaufman_efficiency_ratio', 'custom_range_efficiency', 'wick_ratio',
       'relative_atr', 'bb_width', 'volume_zscore', 'price_volume_ratio',
       'hurst', 'target_volatility_expantion', 'target_chaos',
       'target_neutral_chaos', 'target_strong_move', 'utc_dt',
       'custom_event_time', 'news_count', 'high_impact_count',
       'key_event_count', 'sum_impact', 'sum_event_weight', 'max_event_weight',
       'dominant_event_type', 'event_entropy', 'has_pce', 'has_cpi',
       'has_fomc_pres_conf', 'has_nfp', 'has_gdp', 'has_fomc_rate',
       'has_pmi_services', 'has_core_cpi', 'has_pmi_manufacturing',
       'last_key_event_name', 'last_key_event_hours_ago', 'quarter', 'week',
       'dayofweek', 'day', 'hour', 'minute'],
      dtype='object')

# ML

In [104]:
X = df[['utc_dt', 'quarter', 'week', 'dayofweek', 'day', 'hour', 'minute', 
       'range', 'kaufman_efficiency_ratio', 'custom_range_efficiency', 'wick_ratio',
       'relative_atr', 'bb_width', 'volume_zscore', 'price_volume_ratio',
       'hurst', 'custom_event_time', 'news_count', 'high_impact_count',
       'key_event_count', 'sum_impact', 'sum_event_weight', 'max_event_weight',
       'dominant_event_type', 'event_entropy', 'has_pce', 'has_cpi',
       'has_fomc_pres_conf', 'has_nfp', 'has_gdp', 'has_fomc_rate',
       'has_pmi_services', 'has_core_cpi', 'has_pmi_manufacturing',
       'last_key_event_name', 'last_key_event_hours_ago']]

y = df['target_volatility_expantion']

In [105]:
from catboost import CatBoostClassifier

In [108]:
# Prepare data for CatBoost
# Drop datetime columns as they can't be used directly as features
X_processed = X.drop(['utc_dt', 'custom_event_time'], axis=1)

# Identify categorical features
categorical_features = ['dominant_event_type', 'last_key_event_name']
categorical_indices = [X_processed.columns.get_loc(col) for col in categorical_features if col in X_processed.columns]

# Initialize and fit CatBoost model
model = CatBoostClassifier(
    iterations=1000,
    # task_type="GPU",
    # devices='0',
    learning_rate=0.1,
    depth=6,
    loss_function='Logloss',
    eval_metric='AUC',
    random_seed=42,
    verbose=True,
    cat_features=categorical_indices
)

# Fit the model
model.fit(X_processed, y, cat_features=categorical_indices)

print("Model training completed!")

0:	total: 51.6ms	remaining: 51.6s
1:	total: 95.8ms	remaining: 47.8s
2:	total: 127ms	remaining: 42.2s
3:	total: 164ms	remaining: 40.9s
4:	total: 201ms	remaining: 40s
5:	total: 239ms	remaining: 39.6s
6:	total: 280ms	remaining: 39.7s
7:	total: 320ms	remaining: 39.7s
8:	total: 358ms	remaining: 39.5s
9:	total: 395ms	remaining: 39.1s
10:	total: 428ms	remaining: 38.5s
11:	total: 465ms	remaining: 38.3s
12:	total: 501ms	remaining: 38s
13:	total: 535ms	remaining: 37.7s
14:	total: 571ms	remaining: 37.5s
15:	total: 608ms	remaining: 37.4s
16:	total: 641ms	remaining: 37.1s
17:	total: 675ms	remaining: 36.8s
18:	total: 710ms	remaining: 36.6s
19:	total: 747ms	remaining: 36.6s
20:	total: 780ms	remaining: 36.3s
21:	total: 817ms	remaining: 36.3s
22:	total: 850ms	remaining: 36.1s
23:	total: 884ms	remaining: 36s
24:	total: 917ms	remaining: 35.8s
25:	total: 952ms	remaining: 35.7s
26:	total: 986ms	remaining: 35.5s
27:	total: 1.02s	remaining: 35.5s
28:	total: 1.06s	remaining: 35.5s
29:	total: 1.1s	remaining: 35.5s
30:	total: 1.14s	remaining: 35.5s
31:	total: 1.17s	remaining: 35.5s
32:	total: 1.21s	remaining: 35.5s
33:	total: 1.25s	remaining: 35.4s
34:	total: 1.28s	remaining: 35.4s
35:	total: 1.32s	remaining: 35.4s
36:	total: 1.35s	remaining: 35.2s
37:	total: 1.39s	remaining: 35.2s
38:	total: 1.42s	remaining: 35.1s
39:	total: 1.46s	remaining: 35s
40:	total: 1.49s	remaining: 34.9s
41:	total: 1.53s	remaining: 34.8s
42:	total: 1.56s	remaining: 34.7s
43:	total: 1.59s	remaining: 34.6s
44:	total: 1.63s	remaining: 34.6s
45:	total: 1.66s	remaining: 34.5s
46:	total: 1.7s	remaining: 34.5s
47:	total: 1.74s	remaining: 34.4s
48:	total: 1.77s	remaining: 34.4s
49:	total: 1.81s	remaining: 34.4s
50:	total: 1.84s	remaining: 34.3s
51:	total: 1.88s	remaining: 34.3s
52:	total: 1.92s	remaining: 34.3s
53:	total: 1.95s	remaining: 34.2s
54:	total: 1.99s	remaining: 34.2s
55:	total: 2.03s	remaining: 34.2s
56:	total: 2.07s	remaining: 34.2s
57:	total: 2.1s	remaining: 34.1s
58:	total: 2.14s	remaining: 34.1s
59:	total: 2.17s	remaining: 34s
60:	total: 2.21s	remaining: 34s
61:	total: 2.24s	remaining: 33.9s
62:	total: 2.28s	remaining: 33.9s
63:	total: 2.31s	remaining: 33.8s
64:	total: 2.35s	remaining: 33.8s
65:	total: 2.38s	remaining: 33.7s
66:	total: 2.42s	remaining: 33.7s
67:	total: 2.45s	remaining: 33.6s
68:	total: 2.49s	remaining: 33.6s
69:	total: 2.52s	remaining: 33.5s
70:	total: 2.56s	remaining: 33.5s
71:	total: 2.59s	remaining: 33.4s
72:	total: 2.61s	remaining: 33.1s
73:	total: 2.64s	remaining: 33.1s
74:	total: 2.68s	remaining: 33s
75:	total: 2.71s	remaining: 33s
76:	total: 2.75s	remaining: 32.9s
77:	total: 2.78s	remaining: 32.9s
78:	total: 2.82s	remaining: 32.9s
79:	total: 2.85s	remaining: 32.8s
80:	total: 2.89s	remaining: 32.8s
81:	total: 2.92s	remaining: 32.7s
82:	total: 2.95s	remaining: 32.6s
83:	total: 2.99s	remaining: 32.6s
84:	total: 3.03s	remaining: 32.6s
85:	total: 3.06s	remaining: 32.5s
86:	total: 3.1s	remaining: 32.5s
87:	total: 3.13s	remaining: 32.5s
88:	total: 3.15s	remaining: 32.3s
89:	total: 3.19s	remaining: 32.2s
90:	total: 3.22s	remaining: 32.1s
91:	total: 3.25s	remaining: 32.1s
92:	total: 3.29s	remaining: 32.1s
93:	total: 3.32s	remaining: 32s
94:	total: 3.35s	remaining: 31.9s
95:	total: 3.39s	remaining: 31.9s
96:	total: 3.42s	remaining: 31.8s
97:	total: 3.46s	remaining: 31.9s
98:	total: 3.49s	remaining: 31.8s
99:	total: 3.52s	remaining: 31.7s
100:	total: 3.56s	remaining: 31.7s
101:	total: 3.6s	remaining: 31.7s
102:	total: 3.63s	remaining: 31.6s
103:	total: 3.66s	remaining: 31.6s
104:	total: 3.7s	remaining: 31.5s
105:	total: 3.73s	remaining: 31.5s
106:	total: 3.77s	remaining: 31.4s
107:	total: 3.81s	remaining: 31.4s
108:	total: 3.84s	remaining: 31.4s
109:	total: 3.88s	remaining: 31.4s
110:	total: 3.91s	remaining: 31.4s
111:	total: 3.95s	remaining: 31.4s
112:	total: 3.99s	remaining: 31.3s
113:	total: 4.03s	remaining: 31.3s
114:	total: 4.07s	remaining: 31.3s
115:	total: 4.1s	remaining: 31.3s
116:	total: 4.13s	remaining: 31.2s
117:	total: 4.17s	remaining: 31.2s
118:	total: 4.21s	remaining: 31.2s
119:	total: 4.24s	remaining: 31.1s
120:	total: 4.27s	remaining: 31s
121:	total: 4.31s	remaining: 31s
122:	total: 4.35s	remaining: 31s
123:	total: 4.38s	remaining: 30.9s
124:	total: 4.41s	remaining: 30.9s
125:	total: 4.45s	remaining: 30.9s
126:	total: 4.49s	remaining: 30.8s
127:	total: 4.52s	remaining: 30.8s
128:	total: 4.56s	remaining: 30.8s
129:	total: 4.6s	remaining: 30.8s
130:	total: 4.63s	remaining: 30.7s
131:	total: 4.67s	remaining: 30.7s
132:	total: 4.7s	remaining: 30.7s
133:	total: 4.74s	remaining: 30.6s
134:	total: 4.77s	remaining: 30.6s
135:	total: 4.8s	remaining: 30.5s
136:	total: 4.84s	remaining: 30.5s
137:	total: 4.87s	remaining: 30.4s
138:	total: 4.91s	remaining: 30.4s
139:	total: 4.94s	remaining: 30.4s
140:	total: 4.98s	remaining: 30.3s
141:	total: 5.02s	remaining: 30.3s
142:	total: 5.05s	remaining: 30.3s
143:	total: 5.09s	remaining: 30.3s
144:	total: 5.13s	remaining: 30.2s
145:	total: 5.16s	remaining: 30.2s
146:	total: 5.2s	remaining: 30.2s
147:	total: 5.23s	remaining: 30.1s
148:	total: 5.27s	remaining: 30.1s
149:	total: 5.3s	remaining: 30.1s
150:	total: 5.34s	remaining: 30s
151:	total: 5.38s	remaining: 30s
152:	total: 5.41s	remaining: 30s
153:	total: 5.45s	remaining: 29.9s
154:	total: 5.48s	remaining: 29.9s
155:	total: 5.52s	remaining: 29.9s
156:	total: 5.55s	remaining: 29.8s
157:	total: 5.59s	remaining: 29.8s
158:	total: 5.62s	remaining: 29.7s
159:	total: 5.66s	remaining: 29.7s
160:	total: 5.69s	remaining: 29.7s
161:	total: 5.73s	remaining: 29.6s
162:	total: 5.76s	remaining: 29.6s
163:	total: 5.8s	remaining: 29.5s
164:	total: 5.83s	remaining: 29.5s
165:	total: 5.87s	remaining: 29.5s
166:	total: 5.9s	remaining: 29.4s
167:	total: 5.93s	remaining: 29.4s
168:	total: 5.98s	remaining: 29.4s
169:	total: 6.02s	remaining: 29.4s
170:	total: 6.06s	remaining: 29.4s
171:	total: 6.11s	remaining: 29.4s
172:	total: 6.14s	remaining: 29.4s
173:	total: 6.18s	remaining: 29.3s
174:	total: 6.21s	remaining: 29.3s
175:	total: 6.25s	remaining: 29.3s
176:	total: 6.29s	remaining: 29.2s
177:	total: 6.32s	remaining: 29.2s
178:	total: 6.36s	remaining: 29.1s
179:	total: 6.39s	remaining: 29.1s
180:	total: 6.42s	remaining: 29.1s
181:	total: 6.46s	remaining: 29.1s
182:	total: 6.5s	remaining: 29s
183:	total: 6.54s	remaining: 29s
184:	total: 6.57s	remaining: 28.9s
185:	total: 6.61s	remaining: 28.9s
186:	total: 6.64s	remaining: 28.9s
187:	total: 6.67s	remaining: 28.8s
188:	total: 6.71s	remaining: 28.8s
189:	total: 6.74s	remaining: 28.7s
190:	total: 6.78s	remaining: 28.7s
191:	total: 6.81s	remaining: 28.7s
192:	total: 6.85s	remaining: 28.6s
193:	total: 6.88s	remaining: 28.6s
194:	total: 6.92s	remaining: 28.5s
195:	total: 6.95s	remaining: 28.5s
196:	total: 6.99s	remaining: 28.5s
197:	total: 7.02s	remaining: 28.4s
198:	total: 7.06s	remaining: 28.4s
199:	total: 7.09s	remaining: 28.4s
200:	total: 7.13s	remaining: 28.3s
201:	total: 7.16s	remaining: 28.3s
202:	total: 7.2s	remaining: 28.3s
203:	total: 7.23s	remaining: 28.2s
204:	total: 7.26s	remaining: 28.2s
205:	total: 7.3s	remaining: 28.1s
206:	total: 7.33s	remaining: 28.1s
207:	total: 7.37s	remaining: 28.1s
208:	total: 7.4s	remaining: 28s
209:	total: 7.44s	remaining: 28s
210:	total: 7.47s	remaining: 27.9s
211:	total: 7.51s	remaining: 27.9s
212:	total: 7.55s	remaining: 27.9s
213:	total: 7.58s	remaining: 27.9s
214:	total: 7.61s	remaining: 27.8s
215:	total: 7.65s	remaining: 27.8s
216:	total: 7.68s	remaining: 27.7s
217:	total: 7.72s	remaining: 27.7s
218:	total: 7.75s	remaining: 27.6s
219:	total: 7.79s	remaining: 27.6s
220:	total: 7.82s	remaining: 27.6s
221:	total: 7.87s	remaining: 27.6s
222:	total: 7.9s	remaining: 27.5s
223:	total: 7.94s	remaining: 27.5s
224:	total: 7.98s	remaining: 27.5s
225:	total: 8.02s	remaining: 27.5s
226:	total: 8.05s	remaining: 27.4s
227:	total: 8.09s	remaining: 27.4s
228:	total: 8.13s	remaining: 27.4s
229:	total: 8.16s	remaining: 27.3s
230:	total: 8.2s	remaining: 27.3s
231:	total: 8.23s	remaining: 27.2s
232:	total: 8.26s	remaining: 27.2s
233:	total: 8.3s	remaining: 27.2s
234:	total: 8.33s	remaining: 27.1s
235:	total: 8.37s	remaining: 27.1s
236:	total: 8.41s	remaining: 27.1s
237:	total: 8.45s	remaining: 27s
238:	total: 8.48s	remaining: 27s
239:	total: 8.51s	remaining: 27s
240:	total: 8.55s	remaining: 26.9s
241:	total: 8.58s	remaining: 26.9s
242:	total: 8.62s	remaining: 26.8s
243:	total: 8.65s	remaining: 26.8s
244:	total: 8.69s	remaining: 26.8s
245:	total: 8.72s	remaining: 26.7s
246:	total: 8.76s	remaining: 26.7s
247:	total: 8.8s	remaining: 26.7s
248:	total: 8.83s	remaining: 26.6s
249:	total: 8.87s	remaining: 26.6s
250:	total: 8.9s	remaining: 26.6s
251:	total: 8.93s	remaining: 26.5s
252:	total: 8.97s	remaining: 26.5s
253:	total: 9.01s	remaining: 26.5s
254:	total: 9.05s	remaining: 26.4s
255:	total: 9.08s	remaining: 26.4s
256:	total: 9.11s	remaining: 26.3s
257:	total: 9.15s	remaining: 26.3s
258:	total: 9.18s	remaining: 26.3s
259:	total: 9.22s	remaining: 26.2s
260:	total: 9.25s	remaining: 26.2s
261:	total: 9.29s	remaining: 26.2s
262:	total: 9.32s	remaining: 26.1s
263:	total: 9.36s	remaining: 26.1s
264:	total: 9.39s	remaining: 26.1s
265:	total: 9.43s	remaining: 26s
266:	total: 9.46s	remaining: 26s
267:	total: 9.5s	remaining: 25.9s
268:	total: 9.53s	remaining: 25.9s
269:	total: 9.56s	remaining: 25.9s
270:	total: 9.6s	remaining: 25.8s
271:	total: 9.64s	remaining: 25.8s
272:	total: 9.67s	remaining: 25.8s
273:	total: 9.71s	remaining: 25.7s
274:	total: 9.74s	remaining: 25.7s
275:	total: 9.78s	remaining: 25.6s
276:	total: 9.81s	remaining: 25.6s
277:	total: 9.85s	remaining: 25.6s
278:	total: 9.88s	remaining: 25.5s
279:	total: 9.92s	remaining: 25.5s
280:	total: 9.96s	remaining: 25.5s
281:	total: 9.99s	remaining: 25.4s
282:	total: 10s	remaining: 25.4s
283:	total: 10.1s	remaining: 25.4s
284:	total: 10.1s	remaining: 25.4s
285:	total: 10.2s	remaining: 25.3s
286:	total: 10.2s	remaining: 25.3s
287:	total: 10.2s	remaining: 25.3s
288:	total: 10.3s	remaining: 25.2s
289:	total: 10.3s	remaining: 25.2s
290:	total: 10.3s	remaining: 25.2s
291:	total: 10.4s	remaining: 25.1s
292:	total: 10.4s	remaining: 25.1s
293:	total: 10.4s	remaining: 25s
294:	total: 10.5s	remaining: 25s
295:	total: 10.5s	remaining: 25s
296:	total: 10.5s	remaining: 24.9s
297:	total: 10.6s	remaining: 24.9s
298:	total: 10.6s	remaining: 24.9s
299:	total: 10.6s	remaining: 24.8s
300:	total: 10.7s	remaining: 24.8s
301:	total: 10.7s	remaining: 24.8s
302:	total: 10.7s	remaining: 24.7s
303:	total: 10.8s	remaining: 24.7s
304:	total: 10.8s	remaining: 24.6s
305:	total: 10.8s	remaining: 24.6s
306:	total: 10.9s	remaining: 24.6s
307:	total: 10.9s	remaining: 24.5s
308:	total: 11s	remaining: 24.5s
309:	total: 11s	remaining: 24.5s
310:	total: 11s	remaining: 24.4s
311:	total: 11.1s	remaining: 24.4s
312:	total: 11.1s	remaining: 24.4s
313:	total: 11.1s	remaining: 24.3s
314:	total: 11.2s	remaining: 24.3s
315:	total: 11.2s	remaining: 24.2s
316:	total: 11.2s	remaining: 24.2s
317:	total: 11.3s	remaining: 24.2s
318:	total: 11.3s	remaining: 24.1s
319:	total: 11.3s	remaining: 24.1s
320:	total: 11.4s	remaining: 24.1s
321:	total: 11.4s	remaining: 24s
322:	total: 11.4s	remaining: 24s
323:	total: 11.5s	remaining: 23.9s
324:	total: 11.5s	remaining: 23.9s
325:	total: 11.5s	remaining: 23.9s
326:	total: 11.6s	remaining: 23.8s
327:	total: 11.6s	remaining: 23.8s
328:	total: 11.7s	remaining: 23.8s
329:	total: 11.7s	remaining: 23.7s
330:	total: 11.7s	remaining: 23.7s
331:	total: 11.8s	remaining: 23.7s
332:	total: 11.8s	remaining: 23.6s
333:	total: 11.8s	remaining: 23.6s
334:	total: 11.9s	remaining: 23.5s
335:	total: 11.9s	remaining: 23.5s
336:	total: 11.9s	remaining: 23.5s
337:	total: 12s	remaining: 23.4s
338:	total: 12s	remaining: 23.4s
339:	total: 12s	remaining: 23.4s
340:	total: 12.1s	remaining: 23.3s
341:	total: 12.1s	remaining: 23.3s
342:	total: 12.1s	remaining: 23.3s
343:	total: 12.2s	remaining: 23.2s
344:	total: 12.2s	remaining: 23.2s
345:	total: 12.3s	remaining: 23.2s
346:	total: 12.3s	remaining: 23.1s
347:	total: 12.3s	remaining: 23.1s
348:	total: 12.4s	remaining: 23s
349:	total: 12.4s	remaining: 23s
350:	total: 12.4s	remaining: 23s
351:	total: 12.5s	remaining: 22.9s
352:	total: 12.5s	remaining: 22.9s
353:	total: 12.5s	remaining: 22.9s
354:	total: 12.6s	remaining: 22.8s
355:	total: 12.6s	remaining: 22.8s
356:	total: 12.6s	remaining: 22.8s
357:	total: 12.7s	remaining: 22.7s
358:	total: 12.7s	remaining: 22.7s
359:	total: 12.7s	remaining: 22.7s
360:	total: 12.8s	remaining: 22.6s
361:	total: 12.8s	remaining: 22.6s
362:	total: 12.8s	remaining: 22.5s
363:	total: 12.9s	remaining: 22.5s
364:	total: 12.9s	remaining: 22.5s
365:	total: 13s	remaining: 22.4s
366:	total: 13s	remaining: 22.4s
367:	total: 13s	remaining: 22.4s
368:	total: 13.1s	remaining: 22.3s
369:	total: 13.1s	remaining: 22.3s
370:	total: 13.1s	remaining: 22.3s
371:	total: 13.2s	remaining: 22.2s
372:	total: 13.2s	remaining: 22.2s
373:	total: 13.2s	remaining: 22.2s
374:	total: 13.3s	remaining: 22.1s
375:	total: 13.3s	remaining: 22.1s
376:	total: 13.3s	remaining: 22.1s
377:	total: 13.4s	remaining: 22s
378:	total: 13.4s	remaining: 22s
379:	total: 13.5s	remaining: 22s
380:	total: 13.5s	remaining: 21.9s
381:	total: 13.5s	remaining: 21.9s
382:	total: 13.6s	remaining: 21.9s
383:	total: 13.6s	remaining: 21.8s
384:	total: 13.6s	remaining: 21.8s
385:	total: 13.7s	remaining: 21.8s
386:	total: 13.7s	remaining: 21.7s
387:	total: 13.8s	remaining: 21.7s
388:	total: 13.8s	remaining: 21.7s
389:	total: 13.8s	remaining: 21.6s
390:	total: 13.9s	remaining: 21.6s
391:	total: 13.9s	remaining: 21.6s
392:	total: 13.9s	remaining: 21.5s
393:	total: 14s	remaining: 21.5s
394:	total: 14s	remaining: 21.5s
395:	total: 14s	remaining: 21.4s
396:	total: 14.1s	remaining: 21.4s
397:	total: 14.1s	remaining: 21.3s
398:	total: 14.1s	remaining: 21.3s
399:	total: 14.2s	remaining: 21.3s
400:	total: 14.2s	remaining: 21.2s
401:	total: 14.2s	remaining: 21.2s
402:	total: 14.3s	remaining: 21.2s
403:	total: 14.3s	remaining: 21.1s
404:	total: 14.4s	remaining: 21.1s
405:	total: 14.4s	remaining: 21.1s
406:	total: 14.4s	remaining: 21s
407:	total: 14.5s	remaining: 21s
408:	total: 14.5s	remaining: 21s
409:	total: 14.6s	remaining: 21s
410:	total: 14.6s	remaining: 21s
411:	total: 14.7s	remaining: 20.9s
412:	total: 14.7s	remaining: 20.9s
413:	total: 14.7s	remaining: 20.9s
414:	total: 14.8s	remaining: 20.8s
415:	total: 14.8s	remaining: 20.8s
416:	total: 14.8s	remaining: 20.7s
417:	total: 14.9s	remaining: 20.7s
418:	total: 14.9s	remaining: 20.7s
419:	total: 14.9s	remaining: 20.6s
420:	total: 15s	remaining: 20.6s
421:	total: 15s	remaining: 20.6s
422:	total: 15.1s	remaining: 20.5s
423:	total: 15.1s	remaining: 20.5s
424:	total: 15.1s	remaining: 20.5s
425:	total: 15.2s	remaining: 20.4s
426:	total: 15.2s	remaining: 20.4s
427:	total: 15.2s	remaining: 20.4s
428:	total: 15.3s	remaining: 20.3s
429:	total: 15.3s	remaining: 20.3s
430:	total: 15.3s	remaining: 20.3s
431:	total: 15.4s	remaining: 20.2s
432:	total: 15.4s	remaining: 20.2s
433:	total: 15.5s	remaining: 20.2s
434:	total: 15.5s	remaining: 20.1s
435:	total: 15.5s	remaining: 20.1s
436:	total: 15.6s	remaining: 20s
437:	total: 15.6s	remaining: 20s
438:	total: 15.6s	remaining: 20s
439:	total: 15.7s	remaining: 19.9s
440:	total: 15.7s	remaining: 19.9s
441:	total: 15.7s	remaining: 19.8s
442:	total: 15.8s	remaining: 19.8s
443:	total: 15.8s	remaining: 19.8s
444:	total: 15.8s	remaining: 19.7s
445:	total: 15.9s	remaining: 19.7s
446:	total: 15.9s	remaining: 19.7s
447:	total: 15.9s	remaining: 19.6s
448:	total: 16s	remaining: 19.6s
449:	total: 16s	remaining: 19.6s
450:	total: 16s	remaining: 19.5s
451:	total: 16.1s	remaining: 19.5s
452:	total: 16.1s	remaining: 19.5s
453:	total: 16.2s	remaining: 19.4s
454:	total: 16.2s	remaining: 19.4s
455:	total: 16.2s	remaining: 19.3s
456:	total: 16.3s	remaining: 19.3s
457:	total: 16.3s	remaining: 19.3s
458:	total: 16.3s	remaining: 19.2s
459:	total: 16.4s	remaining: 19.2s
460:	total: 16.4s	remaining: 19.2s
461:	total: 16.4s	remaining: 19.1s
462:	total: 16.5s	remaining: 19.1s
463:	total: 16.5s	remaining: 19.1s
464:	total: 16.5s	remaining: 19s
465:	total: 16.6s	remaining: 19s
466:	total: 16.6s	remaining: 19s
467:	total: 16.6s	remaining: 18.9s
468:	total: 16.7s	remaining: 18.9s
469:	total: 16.7s	remaining: 18.9s
470:	total: 16.8s	remaining: 18.8s
471:	total: 16.8s	remaining: 18.8s
472:	total: 16.8s	remaining: 18.7s
473:	total: 16.9s	remaining: 18.7s
474:	total: 16.9s	remaining: 18.7s
475:	total: 16.9s	remaining: 18.7s
476:	total: 17s	remaining: 18.6s
477:	total: 17s	remaining: 18.6s
478:	total: 17.1s	remaining: 18.6s
479:	total: 17.1s	remaining: 18.5s
480:	total: 17.2s	remaining: 18.5s
481:	total: 17.2s	remaining: 18.5s
482:	total: 17.2s	remaining: 18.4s
483:	total: 17.3s	remaining: 18.4s
484:	total: 17.3s	remaining: 18.4s
485:	total: 17.3s	remaining: 18.3s
486:	total: 17.4s	remaining: 18.3s
487:	total: 17.4s	remaining: 18.3s
488:	total: 17.4s	remaining: 18.2s
489:	total: 17.5s	remaining: 18.2s
490:	total: 17.5s	remaining: 18.2s
491:	total: 17.6s	remaining: 18.1s
492:	total: 17.6s	remaining: 18.1s
493:	total: 17.6s	remaining: 18.1s
494:	total: 17.7s	remaining: 18s
495:	total: 17.7s	remaining: 18s
496:	total: 17.7s	remaining: 17.9s
497:	total: 17.8s	remaining: 17.9s
498:	total: 17.8s	remaining: 17.9s
499:	total: 17.8s	remaining: 17.8s
500:	total: 17.9s	remaining: 17.8s
501:	total: 17.9s	remaining: 17.8s
502:	total: 18s	remaining: 17.7s
503:	total: 18s	remaining: 17.7s
504:	total: 18s	remaining: 17.7s
505:	total: 18.1s	remaining: 17.6s
506:	total: 18.1s	remaining: 17.6s
507:	total: 18.1s	remaining: 17.6s
508:	total: 18.2s	remaining: 17.5s
509:	total: 18.2s	remaining: 17.5s
510:	total: 18.2s	remaining: 17.5s
511:	total: 18.3s	remaining: 17.4s
512:	total: 18.3s	remaining: 17.4s
513:	total: 18.4s	remaining: 17.4s
514:	total: 18.4s	remaining: 17.3s
515:	total: 18.4s	remaining: 17.3s
516:	total: 18.5s	remaining: 17.2s
517:	total: 18.5s	remaining: 17.2s
518:	total: 18.5s	remaining: 17.2s
519:	total: 18.6s	remaining: 17.1s
520:	total: 18.6s	remaining: 17.1s
521:	total: 18.6s	remaining: 17.1s
522:	total: 18.7s	remaining: 17s
523:	total: 18.7s	remaining: 17s
524:	total: 18.7s	remaining: 17s
525:	total: 18.8s	remaining: 16.9s
526:	total: 18.8s	remaining: 16.9s
527:	total: 18.8s	remaining: 16.8s
528:	total: 18.9s	remaining: 16.8s
529:	total: 18.9s	remaining: 16.8s
530:	total: 19s	remaining: 16.7s
531:	total: 19s	remaining: 16.7s
532:	total: 19s	remaining: 16.7s
533:	total: 19.1s	remaining: 16.7s
534:	total: 19.1s	remaining: 16.6s
535:	total: 19.2s	remaining: 16.6s
536:	total: 19.2s	remaining: 16.6s
537:	total: 19.2s	remaining: 16.5s
538:	total: 19.3s	remaining: 16.5s
539:	total: 19.3s	remaining: 16.5s
540:	total: 19.3s	remaining: 16.4s
541:	total: 19.4s	remaining: 16.4s
542:	total: 19.4s	remaining: 16.3s
543:	total: 19.5s	remaining: 16.3s
544:	total: 19.5s	remaining: 16.3s
545:	total: 19.5s	remaining: 16.2s
546:	total: 19.6s	remaining: 16.2s
547:	total: 19.6s	remaining: 16.2s
548:	total: 19.6s	remaining: 16.1s
549:	total: 19.7s	remaining: 16.1s
550:	total: 19.7s	remaining: 16.1s
551:	total: 19.7s	remaining: 16s
552:	total: 19.8s	remaining: 16s
553:	total: 19.8s	remaining: 15.9s
554:	total: 19.8s	remaining: 15.9s
555:	total: 19.9s	remaining: 15.9s
556:	total: 19.9s	remaining: 15.8s
557:	total: 20s	remaining: 15.8s
558:	total: 20s	remaining: 15.8s
559:	total: 20s	remaining: 15.7s
560:	total: 20.1s	remaining: 15.7s
561:	total: 20.1s	remaining: 15.7s
562:	total: 20.1s	remaining: 15.6s
563:	total: 20.2s	remaining: 15.6s
564:	total: 20.2s	remaining: 15.6s
565:	total: 20.2s	remaining: 15.5s
566:	total: 20.3s	remaining: 15.5s
567:	total: 20.3s	remaining: 15.4s
568:	total: 20.3s	remaining: 15.4s
569:	total: 20.4s	remaining: 15.4s
570:	total: 20.4s	remaining: 15.3s
571:	total: 20.4s	remaining: 15.3s
572:	total: 20.5s	remaining: 15.3s
573:	total: 20.5s	remaining: 15.2s
574:	total: 20.6s	remaining: 15.2s
575:	total: 20.6s	remaining: 15.2s
576:	total: 20.6s	remaining: 15.1s
577:	total: 20.7s	remaining: 15.1s
578:	total: 20.7s	remaining: 15s
579:	total: 20.7s	remaining: 15s

In [109]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report, confusion_matrix

In [110]:
# Prepare data for CatBoost
# Drop datetime columns as they can't be used directly as features
X_processed = X.drop(['utc_dt', 'custom_event_time'], axis=1)

# Identify categorical features
categorical_features = ['dominant_event_type', 'last_key_event_name']
categorical_indices = [X_processed.columns.get_loc(col) for col in categorical_features if col in X_processed.columns]

# TimeSeriesSplit for time series cross-validation
n_splits = 5
tscv = TimeSeriesSplit(n_splits=n_splits)

In [111]:
# Store results for each fold
fold_results = []

print(f"Starting TimeSeriesSplit cross-validation with {n_splits} folds...")
print("=" * 80)

for fold, (train_idx, val_idx) in enumerate(tscv.split(X_processed), 1):
    print(f"\nFold {fold}/{n_splits}")
    print(f"Train size: {len(train_idx)}, Validation size: {len(val_idx)}")
    
    # Split data
    X_train, X_val = X_processed.iloc[train_idx], X_processed.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]
    
    # Initialize CatBoost model
    model = CatBoostClassifier(
        iterations=1000,
        # task_type="GPU",
        # devices='0',
        learning_rate=0.1,
        depth=6,
        loss_function='Logloss',
        eval_metric='AUC',
        random_seed=42,
        verbose=100,
        cat_features=categorical_indices,
        early_stopping_rounds=50
    )
    
    # Fit the model with validation set (this will show metrics during training)
    model.fit(
        X_train, y_train,
        eval_set=(X_val, y_val),
        cat_features=categorical_indices,
        use_best_model=True,
        plot=False
    )
    
    # Predictions on validation set
    y_val_pred = model.predict(X_val)
    y_val_pred_proba = model.predict_proba(X_val)[:, 1]
    
    # Calculate metrics
    accuracy = accuracy_score(y_val, y_val_pred)
    precision = precision_score(y_val, y_val_pred, zero_division=0)
    recall = recall_score(y_val, y_val_pred, zero_division=0)
    f1 = f1_score(y_val, y_val_pred, zero_division=0)
    auc = roc_auc_score(y_val, y_val_pred_proba)
    
    fold_results.append({
        'fold': fold,
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'auc': auc
    })
    
    print(f"\nValidation Metrics for Fold {fold}:")
    print(f"  Accuracy:  {accuracy:.4f}")
    print(f"  Precision: {precision:.4f}")
    print(f"  Recall:    {recall:.4f}")
    print(f"  F1-Score:  {f1:.4f}")
    print(f"  AUC:       {auc:.4f}")
    print("-" * 80)

Starting TimeSeriesSplit cross-validation with 5 folds...
================================================================================

Fold 1/5
Train size: 7427, Validation size: 7425
0:	test: 0.8214997	best: 0.8214997 (0)	total: 18.4ms	remaining: 18.3s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.8639022559
bestIteration = 31

Shrink model to first 32 iterations.

Validation Metrics for Fold 1:
  Accuracy:  0.7957
  Precision: 0.8249
  Recall:    0.8161
  F1-Score:  0.8205
  AUC:       0.8639
--------------------------------------------------------------------------------

Fold 2/5
Train size: 14852, Validation size: 7425
0:	test: 0.8087263	best: 0.8087263 (0)	total: 23.9ms	remaining: 23.9s
100:	test: 0.8669051	best: 0.8670122 (95)	total: 2.73s	remaining: 24.3s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.8670121508
bestIteration = 95

Shrink model to first 96 iterations.

Validation Metrics for Fold 2:
  Accuracy:  0.8004
  Precision: 0.8380
  Recall:    0.8317
  F1-Score:  0.8348
  AUC:       0.8670
--------------------------------------------------------------------------------

Fold 3/5
Train size: 22277, Validation size: 7425
0:	test: 0.8511589	best: 0.8511589 (0)	total: 23.8ms	remaining: 23.8s
100:	test: 0.8834091	best: 0.8838253 (78)	total: 2.98s	remaining: 26.5s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.8838252505
bestIteration = 78

Shrink model to first 79 iterations.

Validation Metrics for Fold 3:
  Accuracy:  0.8210
  Precision: 0.8508
  Recall:    0.8518
  F1-Score:  0.8513
  AUC:       0.8838
--------------------------------------------------------------------------------

Fold 4/5
Train size: 29702, Validation size: 7425
0:	test: 0.8446419	best: 0.8446419 (0)	total: 27ms	remaining: 27s
100:	test: 0.8709437	best: 0.8720039 (63)	total: 3.2s	remaining: 28.5s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.8720039496
bestIteration = 63

Shrink model to first 64 iterations.

Validation Metrics for Fold 4:
  Accuracy:  0.8071
  Precision: 0.8309
  Recall:    0.8529
  F1-Score:  0.8417
  AUC:       0.8720
--------------------------------------------------------------------------------

Fold 5/5
Train size: 37127, Validation size: 7425
0:	test: 0.8767089	best: 0.8767089 (0)	total: 30.4ms	remaining: 30.4s
100:	test: 0.8973749	best: 0.8973749 (100)	total: 3.5s	remaining: 31.2s
200:	test: 0.8981540	best: 0.8982827 (182)	total: 6.9s	remaining: 27.4s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.8982827384
bestIteration = 182

Shrink model to first 183 iterations.

Validation Metrics for Fold 5:
  Accuracy:  0.8455
  Precision: 0.8681
  Recall:    0.8769
  F1-Score:  0.8725
  AUC:       0.8983
--------------------------------------------------------------------------------

In [112]:
# Summary of all folds
print("\n" + "=" * 80)
print("CROSS-VALIDATION SUMMARY")
print("=" * 80)

results_df = pd.DataFrame(fold_results)
print("\nMetrics per fold:")
print(results_df.to_string(index=False))

print("\nAverage metrics across all folds:")
print(f"  Accuracy:  {results_df['accuracy'].mean():.4f} (+/- {results_df['accuracy'].std():.4f})")
print(f"  Precision: {results_df['precision'].mean():.4f} (+/- {results_df['precision'].std():.4f})")
print(f"  Recall:    {results_df['recall'].mean():.4f} (+/- {results_df['recall'].std():.4f})")
print(f"  F1-Score:  {results_df['f1'].mean():.4f} (+/- {results_df['f1'].std():.4f})")
print(f"  AUC:       {results_df['auc'].mean():.4f} (+/- {results_df['auc'].std():.4f})")

# Train final model on all data (optional - for production use)
print("\n" + "=" * 80)
print("Training final model on all data...")
print("=" * 80)

final_model = CatBoostClassifier(
    iterations=1000,
    # task_type="GPU",
    # devices='0',
    learning_rate=0.1,
    depth=6,
    loss_function='Logloss',
    eval_metric='AUC',
    random_seed=42,
    verbose=100,
    cat_features=categorical_indices
)

final_model.fit(X_processed, y, cat_features=categorical_indices)

# Final predictions on full dataset
y_pred_final = final_model.predict(X_processed)
y_pred_proba_final = final_model.predict_proba(X_processed)[:, 1]

# Final metrics
final_accuracy = accuracy_score(y, y_pred_final)
final_auc = roc_auc_score(y, y_pred_proba_final)

print(f"\nFinal Model Metrics (on full dataset):")
print(f"  Accuracy:  {final_accuracy:.4f}")
print(f"  AUC:       {final_auc:.4f}")

print("\nClassification Report:")
print(classification_report(y, y_pred_final))

print("\nConfusion Matrix:")
print(confusion_matrix(y, y_pred_final))

print("\nModel training completed!")

================================================================================
CROSS-VALIDATION SUMMARY
================================================================================

Metrics per fold:
 fold  accuracy  precision   recall       f1      auc
    1  0.795690   0.824887 0.816149 0.820495 0.863902
    2  0.800404   0.837995 0.831668 0.834819 0.867012
    3  0.821010   0.850816 0.851769 0.851292 0.883825
    4  0.807138   0.830897 0.852856 0.841733 0.872004
    5  0.845522   0.868142 0.876872 0.872485 0.898283

Average metrics across all folds:
  Accuracy:  0.8140 (+/- 0.0201)
  Precision: 0.8425 (+/- 0.0173)
  Recall:    0.8459 (+/- 0.0231)
  F1-Score:  0.8442 (+/- 0.0194)
  AUC:       0.8770 (+/- 0.0141)

================================================================================
Training final model on all data...
================================================================================
0:	total: 30.1ms	remaining: 30.1s
100:	total: 3.51s	remaining: 31.3s
200:	total: 7.06s	remaining: 28.1s
300:	total: 10.5s	remaining: 24.5s
400:	total: 14s	remaining: 20.9s
500:	total: 17.5s	remaining: 17.5s
600:	total: 21.1s	remaining: 14s
700:	total: 24.7s	remaining: 10.5s
800:	total: 28.2s	remaining: 7s
900:	total: 31.8s	remaining: 3.49s
999:	total: 35.3s	remaining: 0us

Final Model Metrics (on full dataset):
  Accuracy:  0.8838
  AUC:       0.9505

Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.84      0.85     17991
           1       0.89      0.91      0.90     26561

    accuracy                           0.88     44552
   macro avg       0.88      0.88      0.88     44552
weighted avg       0.88      0.88      0.88     44552


Confusion Matrix:
[[15148  2843]
 [ 2335 24226]]

Model training completed!