In [1]:
import pandas as pd
import requests
import time

from tqdm import tqdm
tqdm.pandas()

In [2]:
def get_news_for_a_period(start_date: str, end_date: str, countries: list = ['US', 'FR', 'GB', 'EU', 'AU', 'DE', 'JP', 'CN']):
    start_date += 'T00:00:00'
    end_date += 'T00:00:00'

    url = 'https://economic-calendar.tradingview.com/events'
    headers = {
        'Origin': 'https://in.tradingview.com'
    }
    payload = {
        'from': start_date + '.000Z',
        'to': end_date + '.000Z',
        'countries': ','.join(countries)
    }
    data = requests.get(url, headers=headers, params=payload).json()
    data = pd.DataFrame(data['result'])
    return data

In [7]:
START_DATE = '2024-01-01'
END_DATE = '2024-02-01'

In [138]:
df = get_news_for_a_period(START_DATE, END_DATE)

2024-01-01T00:00:00
2024-01-31T00:00:00

In [153]:
(pd.to_datetime('2024-01-31T00:00:00') - pd.Timedelta('1 day')).isoformat()

'2024-01-30T00:00:00'

In [155]:
df

,id,title,country,indicator,category,period,referenceDate,source,source_url,actual,...,actualRaw,previousRaw,forecastRaw,currency,importance,date,comment,unit,ticker,scale
0,340058,New Year’s Day,AU,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,AUD,-1,2024-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
1,340287,New Year’s Day,CN,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,CNY,-1,2024-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
2,340526,New Year’s Day,EU,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,EUR,-1,2024-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
3,340561,New Year’s Day,FR,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,EUR,-1,2024-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
4,340601,New Year’s Day,DE,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,EUR,-1,2024-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789,338409,Fed Interest Rate Decision,US,Interest Rate,mny,,2024-01-31T00:00:00Z,Federal Reserve,http://www.federalreserve.gov/,5.5,...,5.500000e+00,5.500000e+00,5.5,USD,1,2024-01-31T19:00:00.000Z,"In the United States, the authority to set int...",%,ECONOMICS:USINTR,NaN
790,362860,Fed Press Conference,US,Interest Rate,mny,,None,Federal Reserve,http://www.federalreserve.gov/,NaN,...,NaN,NaN,NaN,USD,1,2024-01-31T19:30:00.000Z,"In the United States, the authority to set int...",NaN,ECONOMICS:USINTR,NaN
791,346193,Judo Bank Manufacturing PMI Final,AU,manufacturing pmi,bsnss,Jan,2024-01-31T00:00:00Z,S&P Global,https://www.pmi.spglobal.com/public,NaN,...,NaN,NaN,NaN,AUD,0,2024-01-31T22:00:00.000Z,The S&P Global Australia Manufacturing PMI is ...,NaN,NaN,NaN
792,342253,Stock Investment by Foreigners,JP,Foreign Stock Investment,mny,Jan/27,2024-01-27T00:00:00Z,Ministry of Finance,http://www.mof.go.jp,720.3,...,7.203000e+11,2.870000e+11,NaN,JPY,-1,2024-01-31T23:50:00.000Z,Foreign Investments in Japanese Stocks refers ...,¥,ECONOMICS:JPFSI,B
793,342254,Foreign Bond Investment,JP,Foreign Bond Investment,mny,Jan/27,2024-01-27T00:00:00Z,Ministry of Finance,http://www.mof.go.jp,382.9,...,3.829000e+11,-4.350000e+10,NaN,JPY,-1,2024-01-31T23:50:00.000Z,The net data shows the difference between acqu...,¥,ECONOMICS:JPFBI,B

In [156]:
df['date'] = pd.to_datetime(df['date'])

In [161]:
df[df['date'] >= '2024-01-30']

,id,title,country,indicator,category,period,referenceDate,source,source_url,actual,...,actualRaw,previousRaw,forecastRaw,currency,importance,date,comment,unit,ticker,scale
677,364580,Retail Sales MoM Prel,AU,Retail Sales MoM,cnsm,Dec,2023-12-31T00:00:00Z,Bureau of Statistics,http://www.abs.gov.au,-2.700,...,-2.700000e+00,1.600000e+00,-1.0,AUD,0,2024-01-30 00:30:00+00:00,"In Australia, the Retail sales report provides...",%,ECONOMICS:AURSMM,NaN
678,339712,2-Year JGB Auction,JP,2 Year Note Yield,bnd,,None,,,0.075,...,7.500000e-02,6.400000e-02,NaN,JPY,-1,2024-01-30 03:35:00+00:00,NaN,%,NaN,NaN
679,346078,GDP Growth Rate YoY Prel,FR,GDP Annual Growth Rate,gdp,Q4,2023-12-31T00:00:00Z,INSEE,https://www.insee.fr,0.700,...,7.000000e-01,6.000000e-01,NaN,EUR,1,2024-01-30 06:30:00+00:00,France is the seventh largest economy in the w...,%,ECONOMICS:FRGDPYY,NaN
680,346079,GDP Growth Rate QoQ Prel,FR,GDP Growth Rate,gdp,Q4,2023-12-31T00:00:00Z,INSEE,https://www.insee.fr,0.000,...,0.000000e+00,0.000000e+00,0.0,EUR,1,2024-01-30 06:30:00+00:00,France is the seventh largest economy in the w...,%,ECONOMICS:FRGDPQQ,NaN
681,346080,Household Consumption MoM,FR,Personal Spending,cnsm,Dec,2023-12-31T00:00:00Z,INSEE,https://www.insee.fr,0.300,...,3.000000e-01,6.000000e-01,0.3,EUR,-1,2024-01-30 06:30:00+00:00,"In France, household consumption refers to hou...",%,ECONOMICS:FRPSP,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789,338409,Fed Interest Rate Decision,US,Interest Rate,mny,,2024-01-31T00:00:00Z,Federal Reserve,http://www.federalreserve.gov/,5.500,...,5.500000e+00,5.500000e+00,5.5,USD,1,2024-01-31 19:00:00+00:00,"In the United States, the authority to set int...",%,ECONOMICS:USINTR,NaN
790,362860,Fed Press Conference,US,Interest Rate,mny,,None,Federal Reserve,http://www.federalreserve.gov/,NaN,...,NaN,NaN,NaN,USD,1,2024-01-31 19:30:00+00:00,"In the United States, the authority to set int...",NaN,ECONOMICS:USINTR,NaN
791,346193,Judo Bank Manufacturing PMI Final,AU,manufacturing pmi,bsnss,Jan,2024-01-31T00:00:00Z,S&P Global,https://www.pmi.spglobal.com/public,NaN,...,NaN,NaN,NaN,AUD,0,2024-01-31 22:00:00+00:00,The S&P Global Australia Manufacturing PMI is ...,NaN,NaN,NaN
792,342253,Stock Investment by Foreigners,JP,Foreign Stock Investment,mny,Jan/27,2024-01-27T00:00:00Z,Ministry of Finance,http://www.mof.go.jp,720.300,...,7.203000e+11,2.870000e+11,NaN,JPY,-1,2024-01-31 23:50:00+00:00,Foreign Investments in Japanese Stocks refers ...,¥,ECONOMICS:JPFSI,B
793,342254,Foreign Bond Investment,JP,Foreign Bond Investment,mny,Jan/27,2024-01-27T00:00:00Z,Ministry of Finance,http://www.mof.go.jp,382.900,...,3.829000e+11,-4.350000e+10,NaN,JPY,-1,2024-01-31 23:50:00+00:00,The net data shows the difference between acqu...,¥,ECONOMICS:JPFBI,B

In [139]:
df.shape

(718, 22)

In [140]:
df.tail()

,id,title,country,indicator,category,period,referenceDate,source,source_url,actual,...,actualRaw,previousRaw,forecastRaw,currency,importance,date,comment,unit,ticker,scale
713,346053,Industrial Production MoM Prel,JP,Industrial Production Mom,bsnss,Dec,2023-12-31T00:00:00Z,Ministry of Economy Trade and Industry (METI),http://www.meti.go.jp,1.8,...,1.8,-0.9,2.4,JPY,0,2024-01-30T23:50:00.000Z,"In Japan, industrial production measures the o...",%,ECONOMICS:JPIPMM,NaN
714,346054,Industrial Production YoY Prel,JP,Industrial Production,bsnss,Dec,2023-12-31T00:00:00Z,Ministry of Economy Trade and Industry (METI),http://www.meti.go.jp,-0.7,...,-0.7,-1.4,NaN,JPY,-1,2024-01-30T23:50:00.000Z,"In Japan, industrial production measures the o...",%,ECONOMICS:JPIPYY,NaN
715,346055,Retail Sales MoM,JP,Retail Sales MoM,cnsm,Dec,2023-12-31T00:00:00Z,Ministry of Economy Trade and Industry (METI),http://www.meti.go.jp,-2.9,...,-2.9,1.0,NaN,JPY,-1,2024-01-30T23:50:00.000Z,"In Japan, the Retail sales report provides an ...",%,ECONOMICS:JPRSMM,NaN
716,346056,Retail Sales YoY,JP,Retail Sales YoY,cnsm,Dec,2023-12-31T00:00:00Z,Ministry of Economy Trade and Industry (METI),http://www.meti.go.jp,2.1,...,2.1,5.4,4.7,JPY,0,2024-01-30T23:50:00.000Z,"In Japan, the year-over-year change in Retail ...",%,ECONOMICS:JPRSYY,NaN
717,363138,BoJ Summary of Opinions,JP,Interest Rate,mny,,None,Central Bank,https://www.boj.or.jp,NaN,...,NaN,NaN,NaN,JPY,0,2024-01-30T23:50:00.000Z,"In Japan, interest rates are set by the Bank o...",NaN,ECONOMICS:JPINTR,NaN

In [38]:
df['date'] = pd.to_datetime(df['date'])

In [39]:
df['date'].max()

Timestamp('2025-02-28 18:00:00+0000', tz='UTC')

In [145]:
df = get_news_for_a_period('2024-01-01', '2024-02-02')

2024-01-01T00:00:00
2024-02-01T00:00:00

In [146]:
df['date'].max()

'2024-01-31T23:50:00.000Z'

In [9]:
PATH_TO_NEWS = "C:/Users/user/Documents/projects/ALGO/algotrading/dataset/economy_calendar/forex_factory_cache.csv"
news = pd.read_csv(PATH_TO_NEWS)
news.head()

,DateTime,Currency,Impact,Event,Actual,Forecast,Previous,Detail
0,2007-01-01T04:30:00+03:30,CNY,High Impact Expected,Manufacturing PMI,54.8,NaN,55.3,Source: CFLP (latest release) | Measures: Leve...
1,2007-01-01T23:59:59+03:30,CAD,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: Canadian banks will be closed in ...
2,2007-01-01T23:59:59+03:30,USD,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: US banks will be closed in observ...
3,2007-01-01T23:59:59+03:30,CNY,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: Chinese banks will be closed in o...
4,2007-01-01T23:59:59+03:30,EUR,Non-Economic,German Bank Holiday,NaN,NaN,NaN,FF Notice: The European Central Bank's Trans-E...

In [147]:
df

,id,title,country,indicator,category,period,referenceDate,source,source_url,actual,...,actualRaw,previousRaw,forecastRaw,currency,importance,date,comment,unit,ticker,scale
0,340058,New Year’s Day,AU,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,AUD,-1,2024-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
1,340287,New Year’s Day,CN,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,CNY,-1,2024-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
2,340526,New Year’s Day,EU,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,EUR,-1,2024-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
3,340561,New Year’s Day,FR,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,EUR,-1,2024-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
4,340601,New Year’s Day,DE,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,EUR,-1,2024-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789,338409,Fed Interest Rate Decision,US,Interest Rate,mny,,2024-01-31T00:00:00Z,Federal Reserve,http://www.federalreserve.gov/,5.5,...,5.500000e+00,5.500000e+00,5.5,USD,1,2024-01-31T19:00:00.000Z,"In the United States, the authority to set int...",%,ECONOMICS:USINTR,NaN
790,362860,Fed Press Conference,US,Interest Rate,mny,,None,Federal Reserve,http://www.federalreserve.gov/,NaN,...,NaN,NaN,NaN,USD,1,2024-01-31T19:30:00.000Z,"In the United States, the authority to set int...",NaN,ECONOMICS:USINTR,NaN
791,346193,Judo Bank Manufacturing PMI Final,AU,manufacturing pmi,bsnss,Jan,2024-01-31T00:00:00Z,S&P Global,https://www.pmi.spglobal.com/public,NaN,...,NaN,NaN,NaN,AUD,0,2024-01-31T22:00:00.000Z,The S&P Global Australia Manufacturing PMI is ...,NaN,NaN,NaN
792,342253,Stock Investment by Foreigners,JP,Foreign Stock Investment,mny,Jan/27,2024-01-27T00:00:00Z,Ministry of Finance,http://www.mof.go.jp,720.3,...,7.203000e+11,2.870000e+11,NaN,JPY,-1,2024-01-31T23:50:00.000Z,Foreign Investments in Japanese Stocks refers ...,¥,ECONOMICS:JPFSI,B
793,342254,Foreign Bond Investment,JP,Foreign Bond Investment,mny,Jan/27,2024-01-27T00:00:00Z,Ministry of Finance,http://www.mof.go.jp,382.9,...,3.829000e+11,-4.350000e+10,NaN,JPY,-1,2024-01-31T23:50:00.000Z,The net data shows the difference between acqu...,¥,ECONOMICS:JPFBI,B

In [143]:
news[(news['DateTime'] > '2024-01-30') & (news['DateTime'] < '2024-02-01')]

,DateTime,Currency,Impact,Event,Actual,Forecast,Previous,Detail
77560,2024-01-30T00:00:00+03:30,EUR,Low Impact Expected,Spanish Flash GDP q/q,0.6%,0.2%,0.4%,Source: National Statistics Institute (latest ...
77561,2024-01-30T00:00:00+03:30,EUR,Medium Impact Expected,Spanish Flash CPI y/y,3.4%,3.0%,3.1%,Source: National Statistics Institute (latest ...
77562,2024-01-30T00:00:00+03:30,EUR,Low Impact Expected,French Flash GDP q/q,0.0%,0.0%,-0.1%,Source: INSEE (latest release) | Measures: Cha...
77563,2024-01-30T00:00:00+03:30,EUR,Low Impact Expected,Italian Prelim GDP q/q,0.2%,0.0%,0.1%,Source: Istat (latest release) | Measures: Cha...
77564,2024-01-30T00:00:00+03:30,GBP,Low Impact Expected,Net Lending to Individuals m/m,0.4B,1.5B,2.1B,Source: Bank of England (latest release) | Mea...
77565,2024-01-30T00:00:00+03:30,GBP,Low Impact Expected,Mortgage Approvals,50K,53K,49K,Source: Bank of England (latest release) | Mea...
77566,2024-01-30T00:00:00+03:30,USD,Low Impact Expected,HPI m/m,0.3%,0.3%,0.3%,Source: FHFA (latest release) | Measures: Chan...
77567,2024-01-30T00:00:00+03:30,USD,High Impact Expected,JOLTS Job Openings,9.03M,8.73M,8.93M,Source: Bureau of Labor Statistics (latest rel...
77568,2024-01-30T03:00:00+03:30,JPY,Low Impact Expected,Unemployment Rate,2.4%,2.5%,2.5%,Source: Statistics Bureau (latest release) | M...
77569,2024-01-30T03:31:00+03:30,GBP,Low Impact Expected,BRC Shop Price Index y/y,2.9%,NaN,4.3%,Source: British Retail Consortium (latest rele...
77570,2024-01-30T04:00:00+03:30,AUD,Medium Impact Expected,Retail Sales m/m,-2.7%,-1.9%,1.6%,Source: Australian Bureau of Statistics (lates...
77571,2024-01-30T10:00:00+03:30,EUR,Low Impact Expected,French Consumer Spending m/m,0.3%,0.0%,0.6%,Source: INSEE (latest release) | Measures: Cha...
77572,2024-01-30T10:30:00+03:30,CHF,Low Impact Expected,Trade Balance,1.25B,2.55B,3.83B,Source: Federal Statistical Office (latest rel...
77573,2024-01-30T11:30:00+03:30,CHF,Low Impact Expected,KOF Economic Barometer,101.5,98.3,98.0,Source: KOF Economic Research Agency (latest r...
77574,2024-01-30T12:30:00+03:30,EUR,Low Impact Expected,German Prelim GDP q/q,-0.3%,-0.3%,0.0%,Source: Destatis (latest release) | Measures: ...
77575,2024-01-30T13:00:00+03:30,GBP,Low Impact Expected,M4 Money Supply m/m,0.5%,0.2%,-0.1%,Source: Bank of England (latest release) | Mea...
77576,2024-01-30T13:30:00+03:30,EUR,Low Impact Expected,Prelim Flash GDP q/q,0.0%,-0.1%,-0.1%,Source: Eurostat (latest release) | Measures: ...
77577,2024-01-30T13:49:00+03:30,EUR,Low Impact Expected,Italian 10-y Bond Auction,3.69|1.7,NaN,4.17|1.4,Source: Department of Treasury (latest release...
77578,2024-01-30T17:30:00+03:30,USD,Medium Impact Expected,S&P/CS Composite-20 HPI y/y,5.4%,5.8%,4.9%,Source: Standard & Poor's (latest release) | M...
77579,2024-01-30T18:30:00+03:30,USD,High Impact Expected,CB Consumer Confidence,114.8,114.2,108.0,Source: The Conference Board Inc. (latest rele...
77580,2024-01-30T19:00:00+03:30,EUR,Low Impact Expected,German Buba President Nagel Speaks,NaN,NaN,NaN,Description: Due to speak at the New Economy F...
77581,2024-01-31T00:00:00+03:30,EUR,Low Impact Expected,Italian Monthly Unemployment Rate,7.2%,7.5%,7.4%,Source: Istat (latest release) | Measures: Per...
77582,2024-01-31T00:00:00+03:30,AUD,High Impact Expected,Trimmed Mean CPI q/q,0.8%,0.9%,1.2%,Source: Reserve Bank of Australia (latest rele...
77583,2024-01-31T00:00:00+03:30,GBP,Low Impact Expected,Nationwide HPI m/m,0.7%,0.1%,0.0%,Source: Nationwide Building Society (latest re...
77584,2024-01-31T00:00:00+03:30,JPY,Low Impact Expected,Retail Sales y/y,2.1%,5.0%,5.4%,Source: METI (latest release) | Measures: Chan...
77585,2024-01-31T00:00:00+03:30,AUD,High Impact Expected,CPI y/y,3.4%,3.7%,4.3%,Source: Australian Bureau of Statistics (lates...
77586,2024-01-31T00:00:00+03:30,JPY,Low Impact Expected,Prelim Industrial Production m/m,1.8%,2.5%,-0.9%,Source: METI (latest release) | Measures: Chan...
77587,2024-01-31T00:00:00+03:30,USD,High Impact Expected,Employment Cost Index q/q,0.9%,1.0%,1.1%,Source: Bureau of Labor Statistics (latest rel...
77588,2024-01-31T00:00:00+03:30,USD,High Impact Expected,FOMC Statement,NaN,NaN,NaN,Source: Federal Reserve (latest release) | Usu...
77589,2024-01-31T00:00:00+03:30,JPY,Low Impact Expected,Housing Starts y/y,-4.0%,-6.6%,-8.5%,Source: MLIT (latest release) | Measures: Chan...
77590,2024-01-31T00:00:00+03:30,EUR,Low Impact Expected,German Retail Sales m/m,-1.6%,0.6%,-0.8%,Source: Destatis (latest release) | Measures: ...
77591,2024-01-31T00:00:00+03:30,CNY,Medium Impact Expected,Non-Manufacturing PMI,50.7,50.6,50.4,Source: CFLP (latest release) | Measures: Leve...
77592,2024-01-31T00:00:00+03:30,AUD,Low Impact Expected,Private Sector Credit m/m,0.4%,0.4%,0.4%,Source: Reserve Bank of Australia (latest rele...
77593,2024-01-31T03:20:00+03:30,JPY,Low Impact Expected,BOJ Summary of Opinions,NaN,NaN,NaN,Source: Bank of Japan (latest release) | Usual...
77594,2024-01-31T03:30:00+03:30,NZD,Low Impact Expected,ANZ Business Confidence,36.6,NaN,33.2,Source: ANZ (latest release) | Measures: Level...
77595,2024-01-31T04:00:00+03:30,AUD,High Impact Expected,CPI q/q,0.6%,0.8%,1.2%,Source: Australian Bureau of Statistics (lates...
77596,2024-01-31T05:00:00+03:30,CNY,High Impact Expected,Manufacturing PMI,49.2,49.3,49.0,Source: CFLP (latest release) | Measures: Leve...
77597,2024-01-31T08:30:00+03:30,JPY,Low Impact Expected,Consumer Confidence,38.0,37.6,37.2,Source: Cabinet Office (latest release) | Meas...
77598,2024-01-31T10:30:00+03:30,EUR,Low Impact Expected,German Import Prices m/m,-1.1%,-0.6%,-0.1%,Source: Destatis (latest release) | Measures: ...
77599,2024-01-31T11:00:00+03:30,CHF,Low Impact Expected,Retail Sales y/y,-0.8%,0.9%,-1.5%,Source: Federal Statistical Office (latest rel...
77600,2024-01-31T11:15:00+03:30,EUR,Low Impact Expected,French Prelim CPI m/m,-0.2%,0.0%,0.1%,Source: INSEE (latest release) | Measures: Cha...
77601,2024-01-31T12:25:00+03:30,EUR,Low Impact Expected,German Unemployment Change,-2K,11K,2K,Source: Federal Employment Agency (latest rele...
77602,2024-01-31T12:30:00+03:30,CHF,Low Impact Expected,UBS Economic Expectations,-19.5,NaN,-23.7,Source: UBS AG (latest release) | Measures: Le...
77603,2024-01-31T14:02:00+03:30,EUR,Low Impact Expected,German 10-y Bond Auction,2.23|1.8,NaN,2.19|1.7,Source: Bundesbank (latest release) | Measures...
77604,2024-01-31T16:45:00+03:30,USD,High Impact Expected,ADP Non-Farm Employment Change,107K,148K,158K,"Source: Automatic Data Processing, Inc. (lates..."
77605,2024-01-31T17:00:00+03:30,CAD,High Impact Expected,GDP m/m,0.2%,0.1%,0.0%,Source: Statistics Canada (latest release) | M...
77606,2024-01-31T18:15:00+03:30,USD,Medium Impact Expected,Chicago PMI,46.0,47.9,46.9,"Source: ISM-Chicago, Inc (latest release) | Me..."
77607,2024-01-31T19:00:00+03:30,USD,Low Impact Expected,Crude Oil Inventories,1.2M,-0.8M,-9.2M,Source: Energy Information Administration (lat...
77608,2024-01-31T22:30:00+03:30,USD,High Impact Expected,Federal Funds Rate,5.50%,5.50%,5.50%,FF Notice: Source maintained a target range of...
77609,2024-01-31T23:00:00+03:30,USD,High Impact Expected,FOMC Press Conference,NaN,NaN,NaN,Source: Federal Reserve (latest release) | Spe...
77610,2024-01-31T23:59:59+03:30,EUR,High Impact Expected,German Prelim CPI m/m,0.2%,0.1%,0.1%,Source: Destatis (latest release) | Measures: ...

In [16]:
news[(news['DateTime'] >= '2025-01-01T00:00:00') & (news['DateTime'] <= '2026-01-01T00:00:00')].shape

(1326, 8)

In [17]:
news['DateTime'].max()

'2025-04-07T22:30:00+04:30'

In [20]:
news[news['DateTime'] >= '2025-01-01']

,DateTime,Currency,Impact,Event,Actual,Forecast,Previous,Detail
82101,2025-01-01T01:00:00+03:30,USD,Low Impact Expected,API Weekly Statistical Bulletin,NaN,NaN,NaN,Source: API (latest release) | Frequency: Rele...
82102,2025-01-01T11:30:00+03:30,GBP,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: UK banks will be closed in observ...
82103,2025-01-01T23:59:59+03:30,USD,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: US banks will be closed in observ...
82104,2025-01-01T23:59:59+03:30,NZD,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: New Zealand banks will be closed ...
82105,2025-01-01T23:59:59+03:30,CAD,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: Canadian banks will be closed in ...
...,...,...,...,...,...,...,...,...
83422,2025-04-07T10:30:00+04:30,CHF,Low Impact Expected,Foreign Currency Reserves,NaN,NaN,735B,Source: Swiss National Bank (latest release) |...
83423,2025-04-07T12:00:00+04:30,EUR,Low Impact Expected,Sentix Investor Confidence,NaN,-8.9,-2.9,Source: Sentix (latest release) | Measures: Le...
83424,2025-04-07T12:30:00+04:30,EUR,Low Impact Expected,Retail Sales m/m,NaN,0.5%,-0.3%,Source: Eurostat (latest release) | Measures: ...
83425,2025-04-07T18:00:00+04:30,CAD,Low Impact Expected,BOC Business Outlook Survey,NaN,NaN,NaN,Source: Bank of Canada (latest release) | Usua...
83426,2025-04-07T22:30:00+04:30,USD,Low Impact Expected,Consumer Credit m/m,NaN,15.2B,18.1B,Source: Federal Reserve (latest release) | Mea...

In [28]:
df

,id,title,country,indicator,category,period,referenceDate,source,source_url,actual,...,actualRaw,previousRaw,forecastRaw,currency,importance,date,comment,ticker,unit,scale
0,366963,New Year’s Day,AU,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,AUD,-1,2025-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
1,366978,New Year’s Day,CN,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,CNY,-1,2025-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
2,366998,New Year’s Day,FR,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,EUR,-1,2025-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
3,367000,New Year’s Day,DE,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,EUR,-1,2025-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
4,367013,New Year’s Day,JP,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,JPY,-1,2025-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,369446,API Crude Oil Stock Change,US,API Crude Oil Stock Change,NaN,Mar/14,2025-03-14T00:00:00Z,American Petroleum Institute (API),http://www.api.org,4.593,...,4.593000e+06,4.247000e+06,1.170000e+06,USD,0,2025-03-18T20:30:00.000Z,Stocks of crude oil refer to the weekly change...,ECONOMICS:USCSC,NaN,M
1996,375309,Machinery Orders MoM,JP,Machinery Orders,bsnss,Jan,2025-01-31T00:00:00Z,Cabinet Office,https://www.cao.go.jp/index-e.html,-3.500,...,-3.500000e+00,-8.000000e-01,-5.000000e-01,JPY,0,2025-03-18T23:50:00.000Z,"In Japan, Machinery Orders measure the month-o...",ECONOMICS:JPMO,%,NaN
1997,375310,Machinery Orders YoY,JP,Machinery Orders YoY,bsnss,Jan,2025-01-31T00:00:00Z,Cabinet Office,https://www.cao.go.jp/index-e.html,4.400,...,4.400000e+00,4.300000e+00,6.900000e+00,JPY,0,2025-03-18T23:50:00.000Z,"In Japan, Machinery Orders YoY measure the yea...",NaN,%,NaN
1998,375468,Imports YoY,JP,Imports YoY,trd,Feb,2025-02-28T00:00:00Z,Ministry of Finance,http://www.mof.go.jp,-0.700,...,-7.000000e-01,1.620000e+01,1.000000e-01,JPY,-1,2025-03-18T23:50:00.000Z,Japan's main imports are mineral fuels (22 per...,ECONOMICS:JPIMPYY,%,NaN
1999,375469,Balance of Trade,JP,Balance of Trade,trd,Feb,2025-02-28T00:00:00Z,Ministry of Finance,https://www.mof.go.jp/english/index.htm,584.500,...,5.845000e+11,-2.736600e+12,7.228000e+11,JPY,1,2025-03-18T23:50:00.000Z,Japan’s trade balance has fluctuated in recent...,ECONOMICS:JPBOT,¥,B

In [188]:
# freq='MS' означает Month Start (начало месяца)
dates = pd.date_range(start='2024-01-01', periods=13, freq='MS').strftime('%Y-%m-%d').tolist()

In [189]:
print(dates)

['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01', '2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01', '2024-09-01', '2024-10-01', '2024-11-01', '2024-12-01', '2025-01-01']

In [190]:
calendar = []
skipped_dates = []
pb = tqdm(range(1, len(dates)))
for i in pb:
    pb.set_description(f'Fetching {start_date} - {end_date}')
    start_date = dates[i - 1]
    end_date = dates[i]
    calendar_chunk = get_news_for_a_period(start_date, end_date)
    if calendar_chunk.empty:
        pb.set_postfix_str('Empty chunk. Sleeping... (5 sec) and try again')
        time.sleep(5)
        calendar_chunk = get_news_for_a_period(start_date, end_date)
        if calendar_chunk.empty:
            pb.set_postfix_str('Calendar chunk is empty again. Skipping...')
            skipped_dates.append((start_date, end_date))
            time.sleep(3)
    calendar.append(calendar_chunk)
    pb.set_postfix_str('Sleeping... (3 sec)')
    time.sleep(3)

calendar = pd.concat(calendar)

Fetching 2024-11-01 - 2024-12-01: 100%|██████████| 12/12 [00:45<00:00,  3.80s/it, Sleeping... (3 sec)]

In [191]:
calendar

,id,title,country,indicator,category,period,referenceDate,source,source_url,actual,...,actualRaw,previousRaw,forecastRaw,currency,importance,date,comment,unit,ticker,scale
0,340058,New Year’s Day,AU,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,AUD,-1,2024-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
1,340287,New Year’s Day,CN,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,CNY,-1,2024-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
2,340526,New Year’s Day,EU,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,EUR,-1,2024-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
3,340561,New Year’s Day,FR,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,EUR,-1,2024-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
4,340601,New Year’s Day,DE,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,EUR,-1,2024-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,366998,New Year’s Day,FR,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,EUR,-1,2025-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
698,367000,New Year’s Day,DE,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,EUR,-1,2025-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
699,367013,New Year’s Day,JP,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,JPY,-1,2025-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
700,367072,New Year’s Day,GB,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,GBP,-1,2025-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN
701,367073,New Year’s Day,US,Holidays,gov,,None,,,NaN,...,NaN,NaN,NaN,USD,-1,2025-01-01T00:00:00.000Z,NaN,NaN,NaN,NaN

In [186]:
# calendar[calendar['date'] < '2026-01-01'].drop_duplicates().to_csv('../dataset/tradingview_economy_calendar/calendar2025.csv', index=False)

In [195]:
calendar[(calendar['date'] >= '2024-01-01') & (calendar['date'] < '2025-01-01')].drop_duplicates().shape

(9394, 22)

In [197]:
news[(news['DateTime'] >= '2023-01-01') & (news['DateTime'] < '2024-01-01')].shape

(4727, 8)

In [3]:
def get_news_for_a_year(date_list: list):
    calendar = []
    skipped_dates = []

    pb = tqdm(range(1, len(date_list)))
    for i in pb:
        start_date = date_list[i - 1]
        end_date = date_list[i]

        pb.set_description(f'Fetching {start_date} - {end_date}')

        calendar_chunk = get_news_for_a_period(start_date, end_date)
        
        if calendar_chunk.empty:
            pb.set_postfix_str('Empty chunk. Sleeping... (5 sec) and try again')
            time.sleep(5)
            calendar_chunk = get_news_for_a_period(start_date, end_date)
            if calendar_chunk.empty:
                pb.set_postfix_str('Calendar chunk is empty again. Skipping...')
                skipped_dates.append((start_date, end_date))
                time.sleep(3)
        
        calendar.append(calendar_chunk)
        pb.set_postfix_str('Sleeping... (3 sec)')
        time.sleep(3)

    calendar = pd.concat(calendar)
    
    if skipped_dates:
        print(skipped_dates)

    return calendar

In [205]:
df = get_news_for_a_period('2013-01-01', '2013-02-01')
df

,id,title,country,indicator,ticker,comment,category,period,referenceDate,source,...,previous,forecast,actualRaw,previousRaw,forecastRaw,currency,importance,date,unit,scale
0,4361,Non Farm Payrolls,US,Non Farm Payrolls,ECONOMICS:USNFP,Nonfarm payrolls is an employment report relea...,lbr,DEC 2012,2012-12-31T00:00:00Z,Bureau of Labour Statistics,...,NaN,NaN,NaN,NaN,NaN,USD,1,2013-01-04T13:30:00.000Z,NaN,NaN
1,4373,Unemployment Rate,US,Unemployment Rate,ECONOMICS:USUR,"In the United States, the unemployment rate me...",lbr,DEC 2012,2012-12-31T00:00:00Z,Bureau of Labour Statistics,...,NaN,NaN,NaN,NaN,NaN,USD,0,2013-01-04T13:30:00.000Z,NaN,NaN
2,22006,Inflation Rate MoM Flash,DE,Inflation Rate Mom,ECONOMICS:DEIRMM,"In Germany, the most important categories in t...",prce,Dec 2013,2013-12-31T00:00:00Z,Federal Statistical Office,...,0.20,NaN,NaN,0.2,NaN,EUR,-1,2013-01-06T13:00:00.000Z,%,NaN
3,26837,Retail Sales ex Fuel MoM,GB,Retail Sales Ex Fuel,ECONOMICS:GBRSEF,"In the United Kingdom, the Retail sales report...",cnsm,Dec 2013,2013-12-31T00:00:00Z,Office for National Statistics,...,NaN,NaN,NaN,NaN,NaN,GBP,-1,2013-01-17T09:30:00.000Z,NaN,NaN
4,26838,Retail Sales ex Fuel YoY,GB,Retail Sales Ex Fuel,ECONOMICS:GBRSEF,"In the United Kingdom, the Retail sales report...",cnsm,Dec 2013,2013-12-31T00:00:00Z,Office for National Statistics,...,NaN,NaN,NaN,NaN,NaN,GBP,-1,2013-01-17T09:30:00.000Z,NaN,NaN
5,26839,Retail Sales ex Fuel YoY,GB,Retail Sales Ex Fuel,ECONOMICS:GBRSEF,"In the United Kingdom, the Retail sales report...",cnsm,Dec 2013,2013-12-31T00:00:00Z,Office for National Statistics,...,NaN,NaN,NaN,NaN,NaN,GBP,-1,2013-01-17T09:30:00.000Z,NaN,NaN
6,26840,Retail Sales ex Fuel MoM,GB,Retail Sales Ex Fuel,ECONOMICS:GBRSEF,"In the United Kingdom, the Retail sales report...",cnsm,Dec 2013,2013-12-31T00:00:00Z,Office for National Statistics,...,NaN,NaN,NaN,NaN,NaN,GBP,-1,2013-01-17T09:30:00.000Z,NaN,NaN
7,26846,Retail Sales ex Fuel YoY,GB,Retail Sales Ex Fuel,ECONOMICS:GBRSEF,"In the United Kingdom, the Retail sales report...",cnsm,Dec,2014-12-31T00:00:00Z,Office for National Statistics,...,NaN,NaN,NaN,NaN,NaN,GBP,-1,2013-01-17T09:30:00.000Z,NaN,NaN
8,179642,Total Vehicle Sales,US,Total Vehicle Sales,ECONOMICS:USTVS,"In the United States, Total Light Vehicle Sale...",bsnss,Jan,2019-01-31T00:00:00Z,Wards Intelligence,...,17.55,17.2,16700000.0,17550000.0,17200000.0,USD,0,2013-01-23T09:30:00.000Z,NaN,M
9,181138,Total Vehicle Sales,US,Total Vehicle Sales,ECONOMICS:USTVS,"In the United States, Total Light Vehicle Sale...",bsnss,Feb,2019-02-28T00:00:00Z,Wards Intelligence,...,16.70,16.8,16600000.0,16700000.0,16800000.0,USD,0,2013-01-23T09:30:00.000Z,NaN,M
10,227125,Fed Harker Speech,US,Interest Rate,ECONOMICS:USINTR,"In the United States, the authority to set int...",mny,,None,Federal Reserve,...,NaN,NaN,NaN,NaN,NaN,USD,0,2013-01-23T09:30:00.000Z,NaN,NaN
11,227863,US-China Trade Talks,US,Calendar,NaN,NaN,gov,,None,,...,NaN,NaN,NaN,NaN,NaN,USD,-1,2013-01-23T09:30:00.000Z,NaN,NaN
12,227864,US-China Trade Talks,US,Calendar,NaN,NaN,gov,,None,,...,NaN,NaN,NaN,NaN,NaN,USD,-1,2013-01-23T09:30:00.000Z,NaN,NaN
13,227897,Fed Chair Powell Speech,US,Interest Rate,ECONOMICS:USINTR,"In the United States, the authority to set int...",mny,,None,Federal Reserve,...,NaN,NaN,NaN,NaN,NaN,USD,0,2013-01-23T09:30:00.000Z,NaN,NaN
14,227986,Fed Evans Speech,US,Interest Rate,ECONOMICS:USINTR,"In the United States, the authority to set int...",mny,,None,Federal Reserve,...,NaN,NaN,NaN,NaN,NaN,USD,0,2013-01-23T09:30:00.000Z,NaN,NaN
15,228014,European Parliament Elections,EU,Calendar,NaN,NaN,gov,,None,,...,NaN,NaN,NaN,NaN,NaN,EUR,0,2013-01-23T09:30:00.000Z,NaN,NaN
16,228015,European Parliament Elections,EU,Calendar,NaN,NaN,gov,,None,,...,NaN,NaN,NaN,NaN,NaN,EUR,0,2013-01-23T09:30:00.000Z,NaN,NaN
17,228083,ECB Mersch Speech,EU,Interest Rate,ECONOMICS:EUINTR,"In the Euro Area, benchmark interest rate is s...",mny,,None,European Central Bank,...,NaN,NaN,NaN,NaN,NaN,EUR,0,2013-01-23T09:30:00.000Z,NaN,NaN
18,228292,ECB Lautenschläger Speech,EU,Interest Rate,ECONOMICS:EUINTR,"In the Euro Area, benchmark interest rate is s...",mny,,None,European Central Bank,...,NaN,NaN,NaN,NaN,NaN,EUR,0,2013-01-23T09:30:00.000Z,NaN,NaN
19,228790,ECB Hakkarainen Speech,EU,Interest Rate,ECONOMICS:EUINTR,"In the Euro Area, benchmark interest rate is s...",mny,,None,European Central Bank,...,NaN,NaN,NaN,NaN,NaN,EUR,0,2013-01-23T09:30:00.000Z,NaN,NaN
20,228832,Fed Harker Speech,US,Interest Rate,ECONOMICS:USINTR,"In the United States, the authority to set int...",mny,,None,Federal Reserve,...,NaN,NaN,NaN,NaN,NaN,USD,0,2013-01-23T09:30:00.000Z,NaN,NaN
21,228854,ECB Cœuré Speech,EU,Interest Rate,ECONOMICS:EUINTR,"In the Euro Area, benchmark interest rate is s...",mny,,None,European Central Bank,...,NaN,NaN,NaN,NaN,NaN,EUR,0,2013-01-23T09:30:00.000Z,NaN,NaN
22,228861,European Council Meeting,EU,Calendar,NaN,NaN,gov,,None,,...,NaN,NaN,NaN,NaN,NaN,EUR,0,2013-01-23T09:30:00.000Z,NaN,NaN
23,229176,Jackson Hole Economic Policy Symposium,US,Interest Rate,ECONOMICS:USINTR,"In the United States, the authority to set int...",mny,,None,Federal Reserve,...,NaN,NaN,NaN,NaN,NaN,USD,0,2013-01-23T09:30:00.000Z,NaN,NaN
24,229249,ECB Guindos Speech,EU,Interest Rate,ECONOMICS:EUINTR,"In the Euro Area, benchmark interest rate is s...",mny,,None,European Central Bank,...,NaN,NaN,NaN,NaN,NaN,EUR,0,2013-01-23T09:30:00.000Z,NaN,NaN
25,229392,ECB Lautenschläger Speech,EU,Interest Rate,ECONOMICS:EUINTR,"In the Euro Area, benchmark interest rate is s...",mny,,None,European Central Bank,...,NaN,NaN,NaN,NaN,NaN,EUR,0,2013-01-23T09:30:00.000Z,NaN,NaN
26,229420,Fed George Speech,US,Interest Rate,ECONOMICS:USINTR,"In the United States, the authority to set int...",mny,,None,Federal Reserve,...,NaN,NaN,NaN,NaN,NaN,USD,0,2013-01-23T09:30:00.000Z,NaN,NaN
27,229520,Brexit Bill Debate,GB,Calendar,NaN,NaN,gov,,None,,...,NaN,NaN,NaN,NaN,NaN,GBP,-1,2013-01-23T09:30:00.000Z,NaN,NaN
28,229521,MPs Vote on Brexit Bill,GB,Calendar,NaN,NaN,gov,,None,,...,NaN,NaN,NaN,NaN,NaN,GBP,-1,2013-01-23T09:30:00.000Z,NaN,NaN
29,229850,ECB President Lagarde Speech,EU,Interest Rate,ECONOMICS:EUINTR,"In the Euro Area, benchmark interest rate is s...",mny,,None,European Central Bank,...,NaN,NaN,NaN,NaN,NaN,EUR,0,2013-01-23T09:30:00.000Z,NaN,NaN
30,3748,Unemployment Rate,GB,Unemployment Rate,ECONOMICS:GBUR,"In the United Kingdom, the headline unemployme...",lbr,NOV 2012,2012-11-30T00:00:00Z,Office for National Statistics,...,NaN,NaN,NaN,NaN,NaN,GBP,0,2013-01-23T09:30:00.000Z,NaN,NaN
31,20331,Housing Starts MoM,US,Calendar,NaN,Housing Starts refer to the number of new resi...,gov,Sep 2013,2013-09-30T00:00:00Z,,...,0.90,NaN,NaN,0.9,NaN,USD,0,2013-01-25T13:30:00.000Z,%,NaN
32,34100,President Obama Speech,US,Calendar,NaN,NaN,gov,,2013-01-31T00:00:00Z,,...,NaN,NaN,NaN,NaN,NaN,USD,-1,2013-01-29T02:00:00.000Z,NaN,NaN

In [40]:
for year in tqdm([2013, 2014, 2015, 2016, 2017, 2018, 2019]):
    print(f'======== {year} ========')
    dates = pd.date_range(start=f'{year}-01-01', periods=13, freq='MS').strftime('%Y-%m-%d').tolist()
    calendar = get_news_for_a_year(dates)
    calendar = calendar[calendar['date'] < dates[-1]].drop_duplicates()
    calendar.to_csv(f'../../../dataset/tradingview_economy_calendar/calendar{year}.csv', index=False)
    time.sleep(3)

  0%|          | 0/7 [00:00<?, ?it/s]

======== 2013 ========

Fetching 2013-12-01 - 2014-01-01: 100%|██████████| 12/12 [00:43<00:00,  3.66s/it, Sleeping... (3 sec)]
 14%|█▍        | 1/7 [00:46<04:41, 46.95s/it]

======== 2014 ========

Fetching 2014-12-01 - 2015-01-01: 100%|██████████| 12/12 [00:44<00:00,  3.67s/it, Sleeping... (3 sec)]
 29%|██▊       | 2/7 [01:34<03:55, 47.05s/it]

======== 2015 ========

Fetching 2015-12-01 - 2016-01-01: 100%|██████████| 12/12 [00:44<00:00,  3.69s/it, Sleeping... (3 sec)]
 43%|████▎     | 3/7 [02:21<03:08, 47.20s/it]

======== 2016 ========

Fetching 2016-12-01 - 2017-01-01: 100%|██████████| 12/12 [00:44<00:00,  3.71s/it, Sleeping... (3 sec)]
 57%|█████▋    | 4/7 [03:09<02:22, 47.38s/it]

======== 2017 ========

Fetching 2017-12-01 - 2018-01-01: 100%|██████████| 12/12 [00:44<00:00,  3.71s/it, Sleeping... (3 sec)]
 71%|███████▏  | 5/7 [03:56<01:34, 47.48s/it]

======== 2018 ========

Fetching 2018-12-01 - 2019-01-01: 100%|██████████| 12/12 [00:45<00:00,  3.76s/it, Sleeping... (3 sec)]
 86%|████████▌ | 6/7 [04:44<00:47, 47.72s/it]

======== 2019 ========

Fetching 2019-12-01 - 2020-01-01: 100%|██████████| 12/12 [00:45<00:00,  3.82s/it, Sleeping... (3 sec)]
100%|██████████| 7/7 [05:33<00:00, 47.70s/it]

In [28]:
year = '2024'
dates = pd.date_range(start=f'{year}-01-01', periods=13, freq='MS').strftime('%Y-%m-%d').tolist()
df25 = get_news_for_a_year(dates)

Fetching 2024-12-01 - 2025-01-01: 100%|██████████| 12/12 [00:46<00:00,  3.85s/it, Sleeping... (3 sec)]

In [30]:
df25 = df25[pd.to_datetime(df25['date']) < '2025-01-01']

In [38]:
df25.shape

(9405, 22)

In [39]:
df25.drop_duplicates().shape

(9394, 22)

In [32]:
import os

In [33]:
df25.to_csv(f'../../../dataset/tradingview_economy_calendar/calendar2024.csv', index=False)

# Unite news and create dataframe for ML learning

In [41]:
import os
from tqdm import tqdm

In [42]:
news_listdir = os.listdir('../../../dataset/tradingview_economy_calendar/')

In [43]:
news_listdir

['calendar2013.csv',
 'calendar2014.csv',
 'calendar2015.csv',
 'calendar2016.csv',
 'calendar2017.csv',
 'calendar2018.csv',
 'calendar2019.csv',
 'calendar2020.csv',
 'calendar2021.csv',
 'calendar2022.csv',
 'calendar2023.csv',
 'calendar2024.csv',
 'calendar2025.csv',
 'tw_calendar.csv']

In [44]:
df = []
for file in tqdm(news_listdir):
    print('\n==================[FILE]==================\n [NAME]', file)
    df_part = pd.read_csv(f'../../../dataset/tradingview_economy_calendar/{file}')
    print('[SHAPE]: ', df_part.shape)
    print('[MIN / MAX DATE]: ', df_part['date'].min(), df_part['date'].max())
    df.append(df_part)
df = pd.concat(df)

 29%|██▊       | 4/14 [00:00<00:00, 36.58it/s]

==================[FILE]==================
 [NAME] calendar2013.csv
[SHAPE]:  (3084, 22)
[MIN / MAX DATE]:  2013-01-04T13:30:00.000Z 2013-12-31T15:00:00.000Z

==================[FILE]==================
 [NAME] calendar2014.csv
[SHAPE]:  (4412, 22)
[MIN / MAX DATE]:  2014-01-01T00:00:00.000Z 2014-12-31T17:00:00.000Z

==================[FILE]==================
 [NAME] calendar2015.csv
[SHAPE]:  (5457, 22)
[MIN / MAX DATE]:  2015-01-01T00:00:00.000Z 2015-12-31T15:30:00.000Z

==================[FILE]==================
 [NAME] calendar2016.csv
[SHAPE]:  (6331, 22)
[MIN / MAX DATE]:  2016-01-01T00:00:00.000Z 2016-12-30T18:00:00.000Z

==================[FILE]==================
 [NAME] calendar2017.csv
[SHAPE]:  (6537, 22)
[MIN / MAX DATE]:  2017-01-01T00:00:00.000Z 2017-12-31T01:00:00.000Z

==================[FILE]==================
 [NAME] calendar2018.csv
[SHAPE]:  (6660, 22)
[MIN / MAX DATE]:  2018-01-01T00:00:00.000Z 2018-12-31T16:30:00.000Z

==================[FILE]==================
 [NAME] calendar2019.csv

 57%|█████▋    | 8/14 [00:00<00:00, 29.79it/s]

[SHAPE]:  (7048, 22)
[MIN / MAX DATE]:  2019-01-01T00:00:00.000Z 2019-12-31T23:30:00.000Z

==================[FILE]==================
 [NAME] calendar2020.csv
[SHAPE]:  (7800, 22)
[MIN / MAX DATE]:  2020-01-01T00:00:00.000Z 2020-12-31T15:30:00.000Z

==================[FILE]==================
 [NAME] calendar2021.csv
[SHAPE]:  (8021, 22)
[MIN / MAX DATE]:  2021-01-01T00:00:00.000Z 2021-12-31T18:00:00.000Z

==================[FILE]==================
 [NAME] calendar2022.csv
[SHAPE]:  (8558, 22)
[MIN / MAX DATE]:  2022-01-01T00:00:00.000Z 2022-12-31T01:30:00.000Z

==================[FILE]==================
 [NAME] calendar2023.csv
[SHAPE]:  (9092, 22)
[MIN / MAX DATE]:  2023-01-01T00:00:00.000Z 2023-12-31T01:30:00.000Z

==================[FILE]==================
 [NAME] calendar2024.csv

 86%|████████▌ | 12/14 [00:00<00:00, 26.10it/s]

[SHAPE]:  (9405, 22)
[MIN / MAX DATE]:  2024-01-01T00:00:00.000Z 2024-12-31T21:30:00.000Z

==================[FILE]==================
 [NAME] calendar2025.csv
[SHAPE]:  (9403, 22)
[MIN / MAX DATE]:  2025-01-01T00:00:00.000Z 2025-12-31T17:00:00.000Z

==================[FILE]==================
 [NAME] tw_calendar.csv

100%|██████████| 14/14 [00:00<00:00, 14.65it/s]

[SHAPE]:  (94189, 22)
[MIN / MAX DATE]:  2013-01-04T13:30:00.000Z 2025-12-31T17:00:00.000Z

In [45]:
df.drop_duplicates().to_csv('../../../dataset/tradingview_economy_calendar/tw_calendar.csv', index=False)

In [15]:
df['importance'].value_counts()

importance
-1    47201
 0    38842
 1     5745
Name: count, dtype: int64

In [16]:
df['importance'].value_counts(normalize=True)

importance
-1    0.514239
 0    0.423171
 1    0.062590
Name: proportion, dtype: float64

# Compare TW (tradingview) news VS FF(forexfactory) news

In [1]:
import pandas as pd

In [33]:
PATH_TO_NEWS = "C:/Users/user/Documents/projects/ALGO/algotrading/dataset/economy_calendar/forex_factory_cache.csv"
ff_news = pd.read_csv(PATH_TO_NEWS)
ff_news.head()

,DateTime,Currency,Impact,Event,Actual,Forecast,Previous,Detail
0,2007-01-01T04:30:00+03:30,CNY,High Impact Expected,Manufacturing PMI,54.8,NaN,55.3,Source: CFLP (latest release) | Measures: Leve...
1,2007-01-01T23:59:59+03:30,CAD,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: Canadian banks will be closed in ...
2,2007-01-01T23:59:59+03:30,USD,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: US banks will be closed in observ...
3,2007-01-01T23:59:59+03:30,CNY,Non-Economic,Bank Holiday,NaN,NaN,NaN,Description: Chinese banks will be closed in o...
4,2007-01-01T23:59:59+03:30,EUR,Non-Economic,German Bank Holiday,NaN,NaN,NaN,FF Notice: The European Central Bank's Trans-E...

In [2]:
PATH_TO_NEWS = r"C:\Users\user\Documents\projects\ALGO\forex_news_bot\dataset\tradingview_economy_calendar\tw_calendar.csv"
tw_news = pd.read_csv(PATH_TO_NEWS)
tw_news = tw_news[['date', 'currency', 'importance', 'title', 'indicator', 'country', 'category', 'actual', 'forecast', 'previous', 'comment', 'source', 'source_url', 'referenceDate', 'period', 'unit', 'scale']]
tw_news.head()

,date,currency,importance,title,indicator,country,category,actual,forecast,previous,comment,source,source_url,referenceDate,period,unit,scale
0,2013-01-04T13:30:00.000Z,USD,1,Non Farm Payrolls,Non Farm Payrolls,US,lbr,NaN,NaN,NaN,Nonfarm payrolls is an employment report relea...,Bureau of Labour Statistics,http://www.bls.gov/,2012-12-31T00:00:00Z,DEC 2012,NaN,NaN
1,2013-01-04T13:30:00.000Z,USD,0,Unemployment Rate,Unemployment Rate,US,lbr,NaN,NaN,NaN,"In the United States, the unemployment rate me...",Bureau of Labour Statistics,http://www.bls.gov/,2012-12-31T00:00:00Z,DEC 2012,NaN,NaN
2,2013-01-06T13:00:00.000Z,EUR,-1,Inflation Rate MoM Flash,Inflation Rate Mom,DE,prce,NaN,NaN,0.2,"In Germany, the most important categories in t...",Federal Statistical Office,https://www.destatis.de,2013-12-31T00:00:00Z,Dec 2013,%,NaN
3,2013-01-17T09:30:00.000Z,GBP,-1,Retail Sales ex Fuel MoM,Retail Sales Ex Fuel,GB,cnsm,NaN,NaN,NaN,"In the United Kingdom, the Retail sales report...",Office for National Statistics,http://www.ons.gov.uk/,2013-12-31T00:00:00Z,Dec 2013,NaN,NaN
4,2013-01-17T09:30:00.000Z,GBP,-1,Retail Sales ex Fuel YoY,Retail Sales Ex Fuel,GB,cnsm,NaN,NaN,NaN,"In the United Kingdom, the Retail sales report...",Office for National Statistics,http://www.ons.gov.uk/,2013-12-31T00:00:00Z,Dec 2013,NaN,NaN

In [3]:
import pytz

moscow_tz = pytz.timezone('Europe/Moscow')

In [4]:
tw_news['utc_dt'] = pd.to_datetime(tw_news['date'], utc=True).dt.tz_convert(moscow_tz)

In [6]:
tw_news = tw_news[['date', 'utc_dt', 'currency', 'importance', 'title', 'indicator', 'country', 'category', 'actual', 'forecast', 'previous', 'comment', 'source', 'source_url', 'referenceDate', 'period', 'unit', 'scale']]

In [7]:
tw_news['date_day'] = pd.to_datetime(tw_news['date']).dt.date

In [8]:
sample_date = '2025-12-16'

In [11]:
tw_news[tw_news['date_day'] == pd.to_datetime(sample_date).date()]

,date,utc_dt,currency,importance,title,indicator,country,category,actual,forecast,previous,comment,source,source_url,referenceDate,period,unit,scale,date_day
91407,2025-12-16T00:30:00.000Z,2025-12-16 03:30:00+03:00,JPY,0,S&P Global Manufacturing PMI Flash,Manufacturing PMI,JP,bsnss,NaN,48.8,NaN,The S&P Global Japan Manufacturing PMI is a mo...,S&P Global,https://www.pmi.spglobal.com/public,2025-12-31T00:00:00Z,Dec,NaN,NaN,2025-12-16
91408,2025-12-16T00:30:00.000Z,2025-12-16 03:30:00+03:00,JPY,-1,S&P Global Composite PMI Flash,Composite PMI,JP,bsnss,NaN,NaN,NaN,The S&P Global Japan Composite PMI Output Inde...,S&P Global,https://www.pmi.spglobal.com/public,2025-12-31T00:00:00Z,Dec,NaN,NaN,2025-12-16
91409,2025-12-16T00:30:00.000Z,2025-12-16 03:30:00+03:00,JPY,0,S&P Global Services PMI Flash,Services PMI,JP,bsnss,NaN,NaN,NaN,The S&P Global Japan Services PMI is a monthly...,S&P Global,NaN,2025-12-31T00:00:00Z,Dec,NaN,NaN,2025-12-16
91410,2025-12-16T07:00:00.000Z,2025-12-16 10:00:00+03:00,GBP,-1,HMRC Payrolls Change,Non Farm Payrolls,GB,lbr,-38.0,NaN,-22.0,"In the UK, the number of payrolled employees i...",Office for National Statistics,http://www.ons.gov.uk/,2025-11-30T00:00:00Z,Nov,NaN,K,2025-12-16
91411,2025-12-16T07:00:00.000Z,2025-12-16 10:00:00+03:00,GBP,-1,Average Earnings excl. Bonus (3Mo/Yr),Average Earnings Excluding Bonus,GB,lbr,4.6,4.5,4.7,"In the United Kingdom, Average Earnings Exclud...",Office for National Statistics,http://www.ons.gov.uk/,2025-10-31T00:00:00Z,Oct,%,NaN,2025-12-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91465,2025-12-16T23:50:00.000Z,2025-12-17 02:50:00+03:00,JPY,0,Machinery Orders YoY,Machinery Orders YoY,JP,bsnss,12.5,3.6,11.6,"In Japan, Machinery Orders YoY measure the yea...",Cabinet Office,https://www.cao.go.jp/index-e.html,2025-10-31T00:00:00Z,Oct,%,NaN,2025-12-16
91466,2025-12-16T23:50:00.000Z,2025-12-17 02:50:00+03:00,JPY,0,Machinery Orders MoM,Machinery Orders,JP,bsnss,7.0,-2.3,4.2,"In Japan, Machinery Orders measure the month-o...",Cabinet Office,https://www.cao.go.jp/index-e.html,2025-10-31T00:00:00Z,Oct,%,NaN,2025-12-16
91467,2025-12-16T23:50:00.000Z,2025-12-17 02:50:00+03:00,JPY,-1,Imports YoY,Imports YoY,JP,trd,1.3,2.5,0.7,Japan's main imports are mineral fuels (22 per...,Ministry of Finance,http://www.mof.go.jp,2025-11-30T00:00:00Z,Nov,%,NaN,2025-12-16
91468,2025-12-16T23:50:00.000Z,2025-12-17 02:50:00+03:00,JPY,0,Exports YoY,Exports YoY,JP,trd,6.1,4.8,3.6,Exports of high technology products have been ...,Ministry of Finance,http://www.mof.go.jp,2025-11-30T00:00:00Z,Nov,%,NaN,2025-12-16
91469,2025-12-16T23:50:00.000Z,2025-12-17 02:50:00+03:00,JPY,1,Balance of Trade,Balance of Trade,JP,trd,322.2,71.2,-226.1,Japan’s trade balance has fluctuated in recent...,Ministry of Finance,https://www.mof.go.jp/english/index.htm,2025-11-30T00:00:00Z,Nov,¥,B,2025-12-16